import type { ExamSkillEvidence, ExamSkillSourceEvidence } from "./model";

const evidence = (
  sourceId: string,
  strength: number,
  note: string,
): ExamSkillSourceEvidence => ({ sourceId, strength, note });

const current = evidence(
  "current-exam-details",
  1,
  "Current exam scope and comprehensive 60-MCQ format.",
);
const course = evidence(
  "current-course-outline-2025",
  1,
  "Current course material remains the source of model truth.",
);
const final2020 = evidence(
  "actual-final-2020",
  1,
  "Directly tested in the public 2020 final preview.",
);
const practice = evidence(
  "final-practice-2018-19",
  1,
  "Repeated or closely practised in course-specific final MCQ material.",
);
const sample = evidence(
  "sample-final-2020",
  0.9,
  "Integrated final-style reasoning signal.",
);
const recent = evidence(
  "recent-course-assessments",
  0.8,
  "Supported by current lecture/tutorial/data-exercise material.",
);

export const examSkillEvidence: readonly ExamSkillEvidence[] = Object.freeze([
  {
    id: "critical-ad-as-self-correction",
    label: "AD-AS demand shocks and self-correction",
    conceptIds: [
      "aggregate-demand",
      "demand-shock",
      "self-correction",
      "long-run-equilibrium",
      "inflation-dynamics",
      "output-gap",
    ],
    cardIds: ["ch08-006", "ch08-018", "ch08-021", "ch08-017", "mix-020"],
    questionIds: ["mix-020", "auth-ch08-007", "auth-ch08-008"],
    chapterHints: [8],
    tier: "critical",
    crossChapterMechanism: true,
    sourceEvidence: [current, course, final2020, practice, sample],
  },
  {
    id: "critical-supply-shock-policy-tradeoff",
    label: "Adverse supply shocks and policy trade-offs",
    conceptIds: [
      "adverse-supply-shock",
      "supply-shock",
      "demand-stabilisation",
      "accommodating-inflation",
      "inflation-target",
      "aggregate-supply",
    ],
    cardIds: ["ch08-022", "ch08-024", "ch08-025", "ch08-028", "mix-019"],
    questionIds: ["mix-019", "auth-ch08-006", "auth-stim-ch08-002"],
    chapterHints: [8],
    tier: "critical",
    crossChapterMechanism: true,
    sourceEvidence: [current, course, final2020, practice, recent],
  },
  {
    id: "critical-fx-quotes-and-market",
    label: "FX quote conventions and demand/supply",
    conceptIds: [
      "nominal-exchange-rate",
      "aud-quotation",
      "exchange-rate",
      "appreciation",
      "currency-depreciation",
      "foreign-exchange-market",
      "aud-demand",
      "aud-supply",
    ],
    cardIds: [
      "ch09-016",
      "ch09-017",
      "ch09-018",
      "ch09-019",
      "ch09-029",
      "ch09-030",
      "ch09-031",
      "ch09-032",
      "mix-023",
      "mix-024",
    ],
    questionIds: [
      "mix-023",
      "mix-024",
      "auth-ch09-005",
      "auth-stim-ch09-001",
      "auth-stim-ch09-003",
    ],
    chapterHints: [9],
    tier: "critical",
    crossChapterMechanism: true,
    sourceEvidence: [current, course, final2020, practice],
  },
  {
    id: "critical-real-versus-nominal-exchange-rate",
    label: "Nominal versus real exchange rates",
    conceptIds: [
      "real-exchange-rate",
      "real-appreciation",
      "nominal-exchange-rate",
      "price-level",
    ],
    cardIds: ["ch09-022", "ch09-023"],
    questionIds: ["auth-ch09-007"],
    chapterHints: [9],
    tier: "critical",
    sourceEvidence: [current, course, final2020, practice],
  },
  {
    id: "critical-loop-ppp-relative-inflation",
    label: "LOOP, PPP and relative inflation",
    conceptIds: [
      "law-one-price",
      "purchasing-power-parity",
      "relative-ppp",
      "ppp-limitations",
    ],
    cardIds: ["ch09-024", "ch09-025", "ch09-026", "ch09-027", "ch09-028"],
    questionIds: ["auth-ch09-003", "auth-ch09-008", "auth-ch09-009"],
    chapterHints: [9],
    tier: "critical",
    crossChapterMechanism: true,
    sourceEvidence: [current, course, final2020, practice],
  },
  {
    id: "critical-bop-current-account",
    label: "BOP, current account and saving identity",
    conceptIds: [
      "balance-of-payments",
      "current-account",
      "trade-balance",
      "financial-account",
      "bop-identity",
      "open-economy-saving-identity",
    ],
    cardIds: [
      "ch09-001",
      "ch09-002",
      "ch09-003",
      "ch09-006",
      "ch09-007",
      "ch09-008",
      "ch09-009",
      "mix-021",
    ],
    questionIds: ["mix-021", "auth-ch09-001", "auth-ch09-002"],
    chapterHints: [9],
    tier: "critical",
    crossChapterMechanism: true,
    sourceEvidence: [current, course, final2020, practice],
  },
  {
    id: "critical-fixed-peg-intervention",
    label: "Fixed exchange rates and peg intervention",
    conceptIds: [
      "fixed-exchange-rate",
      "overvalued-peg",
      "undervalued-peg",
      "defending-peg",
      "foreign-exchange-market",
    ],
    cardIds: ["ch09-035", "ch09-036", "ch09-037", "ch09-039", "mix-025"],
    questionIds: ["mix-025", "auth-stim-ch09-002"],
    chapterHints: [9],
    tier: "critical",
    crossChapterMechanism: true,
    sourceEvidence: [current, course, final2020, practice],
  },
  {
    id: "critical-speculative-attack-defence",
    label: "Speculative attack and peg defence",
    conceptIds: [
      "speculative-attack",
      "fixed-exchange-rate",
      "defending-peg",
      "overvalued-peg",
    ],
    cardIds: ["ch09-036", "ch09-038", "ch09-039"],
    questionIds: ["auth-ch09-012"],
    chapterHints: [9],
    tier: "critical",
    crossChapterMechanism: true,
    sourceEvidence: [current, course, final2020, practice],
  },
  {
    id: "critical-cobb-douglas-production",
    label: "Cobb-Douglas and production functions",
    conceptIds: [
      "production-function",
      "cobb-douglas",
      "constant-returns-to-scale",
      "diminishing-marginal-product",
      "output-per-worker",
    ],
    cardIds: ["ch10-008", "ch10-009", "ch10-010", "ch10-011", "ch10-014"],
    questionIds: [
      "mix-027",
      "auth-ch10-005",
      "auth-stim-ch10-001",
      "auth-stim-ch10-002",
    ],
    chapterHints: [10],
    tier: "critical",
    sourceEvidence: [current, course, final2020, practice],
  },
  {
    id: "critical-growth-accounting-tfp",
    label: "Growth accounting and TFP",
    conceptIds: [
      "growth-accounting",
      "total-factor-productivity",
      "productivity",
      "labour-productivity",
    ],
    cardIds: ["ch10-018", "ch10-025", "ch10-026", "ch10-027"],
    questionIds: ["mix-026", "auth-ch10-004", "auth-stim-ch10-003"],
    chapterHints: [10],
    tier: "critical",
    sourceEvidence: [current, course, final2020, practice],
  },
  {
    id: "critical-capital-versus-technology",
    label: "Capital deepening versus sustained technology growth",
    conceptIds: [
      "capital-deepening",
      "capital-accumulation-limits",
      "technology-ideas",
      "total-factor-productivity",
      "productivity",
    ],
    cardIds: ["ch10-015", "ch10-016", "ch10-019", "mix-028"],
    questionIds: ["mix-028", "auth-ch10-004", "auth-stim-ch10-002"],
    chapterHints: [10],
    tier: "critical",
    crossChapterMechanism: true,
    sourceEvidence: [current, course, final2020, practice],
  },
  {
    id: "critical-trade-weighted-index",
    label: "Trade-weighted index and competitiveness",
    conceptIds: [
      "trade-weighted-index",
      "real-exchange-rate",
      "real-appreciation",
      "purchasing-power-parity",
      "net-exports",
    ],
    cardIds: ["ch09-041", "ch09-022", "ch09-023", "ch09-026"],
    questionIds: ["auth-ch09-011"],
    chapterHints: [9],
    tier: "critical",
    crossChapterMechanism: true,
    sourceEvidence: [current, course, practice, recent],
  },
  {
    id: "very-high-bank-deposit-creation",
    label: "Bank balance sheets and deposit creation",
    conceptIds: [
      "bank-balance-sheet",
      "bank-lending",
      "money-creation",
      "deposit",
      "reserves",
    ],
    cardIds: ["ch06-015", "ch06-017", "mix-014"],
    questionIds: ["mix-014", "auth-ch06-006", "auth-ch06-007"],
    chapterHints: [6],
    crossChapterMechanism: true,
    tier: "very-high",
    sourceEvidence: [current, course, final2020, practice],
  },
  {
    id: "very-high-bank-risk-chain",
    label: "Bank leverage, solvency, runs and safety-net regulation",
    conceptIds: [
      "bank-leverage",
      "solvency",
      "liquidity",
      "bank-run",
      "deposit-insurance",
      "prudential-regulation",
    ],
    cardIds: ["ch06-019", "ch06-021", "ch06-022", "ch06-023", "ch06-024", "ch06-025"],
    questionIds: ["auth-ch06-008", "auth-ch06-012"],
    chapterHints: [6],
    crossChapterMechanism: true,
    tier: "very-high",
    sourceEvidence: [current, course, final2020, practice],
  },
  {
    id: "very-high-money-destruction",
    label: "Money destruction through repayment and write-off distinctions",
    conceptIds: [
      "money-destruction",
      "money-creation",
      "bank-lending",
      "bank-balance-sheet",
      "deposit",
      "money-stock",
    ],
    cardIds: ["ch06-032", "ch06-017"],
    questionIds: ["auth-ch06-011"],
    chapterHints: [6],
    crossChapterMechanism: true,
    tier: "very-high",
    sourceEvidence: [current, course, practice, recent],
  },
  {
    id: "very-high-prf-taylor",
    label: "PRF, Taylor rule and Taylor principle",
    conceptIds: [
      "policy-reaction-function",
      "taylor-rule",
      "taylor-principle",
      "output-gap",
      "inflation-target",
    ],
    cardIds: ["ch07-022", "ch07-023", "ch07-024", "ch07-026", "ch07-027"],
    questionIds: [
      "auth-ch07-009",
      "auth-ch07-010",
      "auth-stim-ch07-002",
      "mix-017",
      "mix-030",
    ],
    chapterHints: [7],
    crossChapterMechanism: true,
    tier: "very-high",
    sourceEvidence: [current, course, final2020, practice],
  },
  {
    id: "very-high-zlb-deflation-fisher",
    label: "PRF, deflation, ZLB and the Fisher relation",
    conceptIds: [
      "zero-lower-bound",
      "nominal-interest-rate",
      "real-interest-rate",
      "inflation",
      "deflation",
      "inflation-expectations",
      "policy-reaction-function",
    ],
    cardIds: ["ch03-006", "ch03-007", "ch03-008", "ch07-025", "ch07-026"],
    questionIds: ["auth-ch01-010", "auth-ch03-002", "auth-ch03-003", "auth-ch07-012"],
    chapterHints: [3, 7],
    crossChapterMechanism: true,
    tier: "very-high",
    sourceEvidence: [current, course, final2020, practice],
  },
  {
    id: "very-high-monetary-transmission",
    label: "Monetary transmission through rates and AD",
    conceptIds: [
      "cash-rate",
      "monetary-transmission",
      "real-rate-channel",
      "yield-curve",
      "bond-yield",
      "expectations-hypothesis",
      "aggregate-demand",
    ],
    cardIds: ["ch07-005", "ch07-016", "ch07-018", "ch07-019"],
    questionIds: ["auth-ch07-002", "auth-ch07-007", "auth-ch07-008", "auth-ch09-010"],
    chapterHints: [7, 8, 9],
    crossChapterMechanism: true,
    tier: "very-high",
    sourceEvidence: [current, course, final2020, practice],
  },
  {
    id: "very-high-cash-rate-security-market",
    label: "Cash rate to short-term security price and yield",
    conceptIds: [
      "cash-rate-security-transmission",
      "cash-rate",
      "bond-price",
      "bond-yield",
      "expectations-hypothesis",
    ],
    cardIds: ["ch07-029", "ch06-004", "ch07-018", "ch07-019"],
    questionIds: ["auth-ch07-011", "auth-stim-ch06-001"],
    chapterHints: [7],
    crossChapterMechanism: true,
    tier: "very-high",
    sourceEvidence: [current, course, practice, recent],
  },
  {
    id: "very-high-small-open-fiscal",
    label: "Small-open saving, investment and fiscal interaction",
    conceptIds: [
      "small-open-economy",
      "open-economy-saving-identity",
      "national-saving",
      "public-saving",
      "current-account",
      "macro-investment",
    ],
    cardIds: ["ch09-010", "ch09-013", "ch09-014", "ch09-015", "mix-022"],
    questionIds: ["mix-006", "mix-021", "mix-022", "auth-ch03-009", "auth-ch09-004"],
    chapterHints: [3, 9],
    crossChapterMechanism: true,
    tier: "very-high",
    sourceEvidence: [current, course, final2020, practice],
  },
  {
    id: "very-high-rba-corridor-omo",
    label: "RBA cash-rate corridor and OMO mechanics",
    conceptIds: [
      "cash-rate-corridor",
      "reserve-demand",
      "settlement-balances",
      "open-market-operation",
      "open-market-purchase",
      "open-market-sale",
      "cash-rate-target",
    ],
    cardIds: ["ch07-007", "ch07-009", "ch07-011", "ch07-012", "ch07-014"],
    questionIds: [
      "mix-016",
      "auth-ch07-005",
      "auth-ch07-006",
      "auth-ch07-007",
      "auth-stim-ch07-001",
    ],
    chapterHints: [7],
    crossChapterMechanism: true,
    tier: "very-high",
    sourceEvidence: [current, course, practice, recent],
  },
  {
    id: "very-high-growth-convergence",
    label: "Growth catch-up and convergence",
    conceptIds: [
      "convergence",
      "catch-up-growth",
      "economic-growth",
      "technology-ideas",
      "capital-deepening",
    ],
    cardIds: ["ch10-007", "ch10-029"],
    questionIds: ["auth-ch10-010"],
    chapterHints: [10],
    tier: "very-high",
    sourceEvidence: [current, course, practice, recent],
  },
  {
    id: "core-gdp-value-added",
    label: "GDP, value added and nominal-real measurement",
    conceptIds: [
      "gross-domestic-product",
      "intermediate-good",
      "value-added",
      "expenditure-approach",
      "real-gdp",
      "gdp-deflator",
      "nominal-gdp",
    ],
    cardIds: ["ch01-001", "ch01-005", "ch01-006", "ch01-007", "ch01-015"],
    questionIds: ["auth-ch01-001", "auth-ch01-002", "auth-ch01-005", "auth-ch01-007"],
    chapterHints: [1],
    tier: "core",
    sourceEvidence: [current, course, final2020, practice],
  },
  {
    id: "core-cpi-inflation-deflation",
    label: "CPI, inflation and deflation calculations",
    conceptIds: ["cpi", "inflation", "price-level", "percentage-change", "deflation"],
    cardIds: ["ch01-018", "ch01-019", "ch01-027", "ch01-033"],
    questionIds: [
      "auth-ch01-006",
      "auth-ch01-009",
      "auth-ch01-010",
      "auth-stim-ch01-001",
    ],
    chapterHints: [1],
    tier: "core",
    sourceEvidence: [current, course, final2020, practice],
  },
  {
    id: "core-labour-wage-floor",
    label: "Labour statistics and wage-floor model",
    conceptIds: [
      "unemployment-rate",
      "labour-force",
      "participation-rate",
      "labour-demand",
      "labour-supply",
      "wage-floor",
    ],
    cardIds: ["ch02-004", "ch02-007", "ch02-025", "ch02-026", "ch02-027"],
    questionIds: [
      "auth-ch02-001",
      "auth-ch02-004",
      "auth-ch02-011",
      "auth-stim-ch02-001",
      "auth-stim-ch02-002",
    ],
    chapterHints: [2],
    crossChapterMechanism: true,
    tier: "core",
    sourceEvidence: [current, course, final2020, practice],
  },
  {
    id: "core-pae-multiplier-inventories",
    label: "PAE, inventories and the multiplier",
    conceptIds: [
      "pae-equilibrium",
      "planned-aggregate-expenditure",
      "inventory",
      "unplanned-inventory-change",
      "output-adjustment",
      "multiplier",
    ],
    cardIds: ["ch04-004", "ch04-006", "ch04-016", "ch04-019", "ch04-021", "ch04-022"],
    questionIds: [
      "auth-ch04-006",
      "auth-ch04-008",
      "auth-stim-ch04-001",
      "auth-stim-ch04-002",
      "auth-stim-ch04-003",
    ],
    chapterHints: [4],
    tier: "core",
    sourceEvidence: [current, course, sample, recent],
  },
  {
    id: "core-fiscal-multipliers-debt",
    label: "Fiscal multipliers, stabilisers and debt",
    conceptIds: [
      "fiscal-policy",
      "government-spending-multiplier",
      "automatic-stabilisers",
      "debt-gdp",
      "debt-dynamics",
      "debt-sustainability",
    ],
    cardIds: ["ch05-007", "ch05-012", "ch05-013", "ch05-024", "ch05-026"],
    questionIds: [
      "auth-ch05-003",
      "auth-ch05-006",
      "auth-stim-ch05-002",
      "auth-stim-ch05-003",
    ],
    chapterHints: [5],
    tier: "core",
    sourceEvidence: [current, course, sample, recent],
  },
  {
    id: "core-bond-price-yield",
    label: "Bond price and yield",
    conceptIds: ["bond", "bond-price", "bond-yield", "interest-rate", "present-value"],
    cardIds: ["ch06-003", "ch06-004", "mix-012"],
    questionIds: ["mix-012", "auth-ch06-002", "auth-stim-ch06-001"],
    chapterHints: [6],
    tier: "core",
    sourceEvidence: [current, course, practice, recent],
  },
  {
    id: "core-fisher-real-rate",
    label: "Fisher real-rate reasoning",
    conceptIds: [
      "nominal-interest-rate",
      "real-interest-rate",
      "fisher-relationship",
      "inflation-expectations",
    ],
    cardIds: ["ch03-006", "ch03-007", "ch03-008"],
    questionIds: ["auth-ch03-002", "auth-ch03-003", "auth-stim-ch03-003"],
    chapterHints: [3, 7],
    tier: "core",
    sourceEvidence: [current, course, final2020, practice],
  },
]);

export const examSkillById: ReadonlyMap<string, ExamSkillEvidence> = new Map(
  examSkillEvidence.map((skill) => [skill.id, skill]),
);
