import type { ExamQuestionStyle, FourRationales } from "./model";

export const canonicalMcqStyles: Readonly<Record<string, ExamQuestionStyle>> = {
  "ch01-002": "concept",
  "mix-001": "concept",
  "mix-002": "calculation",
  "mix-003": "scenario",
  "mix-004": "calculation",
  "mix-005": "concept",
  "mix-006": "sequence",
  "mix-007": "sequence",
  "mix-008": "calculation",
  "mix-009": "calculation",
  "mix-010": "concept",
  "mix-011": "model_discrimination",
  "mix-012": "scenario",
  "mix-013": "model_discrimination",
  "mix-014": "scenario",
  "mix-015": "calculation",
  "mix-016": "scenario",
  "mix-017": "scenario",
  "mix-018": "model_discrimination",
  "mix-019": "scenario",
  "mix-020": "sequence",
  "mix-021": "calculation",
  "mix-022": "model_discrimination",
  "mix-023": "concept",
  "mix-024": "scenario",
  "mix-025": "scenario",
  "mix-026": "calculation",
  "mix-027": "model_discrimination",
  "mix-028": "concept",
  "mix-029": "model_discrimination",
  "mix-030": "sequence",
};

export const canonicalMcqChoiceRationales: Readonly<Record<string, FourRationales>> = {
  "ch01-002": [
    "This includes transactions such as used-good sales and financial trades that are not current production, and it does not require the output to be final or domestic.",
    "This is too broad because intermediate goods are included even though their value is already embodied in final output; it also omits the domestic-location requirement.",
    "This can include imported final goods and can omit goods produced for inventory rather than purchased during the year, so it is not the GDP definition.",
    "GDP is the market value of final goods and services produced within the country during the period, which excludes double counting and foreign production.",
  ],
  "mix-001": [
    "A used laptop is an existing asset; its resale transfers ownership rather than recording current production.",
    "Buying existing shares is a financial transaction, not expenditure on newly produced final goods or services.",
    "A newly produced Australian machine is current domestic production recorded as business investment.",
    "An age pension is a transfer payment. It can affect later consumption, but the transfer itself is not government purchase of current output.",
  ],
  "mix-002": [
    "This treats the price rise as if it were a fall in output and reverses both the direction and approximate size of the real change.",
    "This subtracts the price growth from nominal growth but reverses the direction; nominal growth above inflation implies positive real growth.",
    "Real growth is approximately nominal growth minus deflator inflation, 8% - 5% = 3%; the exact calculation is about 2.86%.",
    "Adding the two rates confuses nominal growth with the price component; real growth is not 8% + 5%.",
  ],
  "mix-003": [
    "They do not have a job, so they are not employed under the standard classification.",
    "Active search is required for measured unemployment; stopping because no job is believed available makes this person discouraged and outside the labour force.",
    "A discouraged worker is classified as not in the labour force, even though broader underutilisation may be present.",
    "Structural unemployment is a type of unemployment, not a labour-force status; this person is not counted as unemployed while not actively searching.",
  ],
  "mix-004": [
    "The output gap is negative when unemployment is above the natural rate; the positive sign reverses Okun’s-law direction.",
    "This uses the unemployment gap itself as the output gap and omits multiplication by β.",
    "This has the right negative direction but uses β=1 instead of the stated β=2.",
    "Using output gap = -β(u-u*) gives -2 × 2 = -4%.",
  ],
  "mix-005": [
    "Buying existing shares reallocates ownership of a financial asset and does not create new capital in the national accounts.",
    "A deposit records household saving, but the deposit itself is not newly produced physical capital or inventory.",
    "A newly built warehouse is newly produced capital and is therefore macroeconomic investment.",
    "A government bond purchase is a financial transaction; it does not equal government or private investment in GDP.",
  ],
  "mix-006": [
    "A deficit reduces national saving, so the closed-economy saving schedule shifts left rather than right; the resulting rate rises.",
    "This is the closed-economy crowding-out sequence: lower saving raises the equilibrating real rate and reduces private investment.",
    "The deficit does not directly shift investment right; investment falls after the higher real rate moves along its demand curve.",
    "An investment shift is not the direct effect of the deficit, and the stated rate direction is reversed.",
  ],
  "mix-007": [
    "When PAE is below output, goods are left unsold and inventories accumulate rather than fall.",
    "Unplanned inventory accumulation signals excess production, so firms reduce output toward the PAE equilibrium.",
    "Inventory depletion signals excess demand and would support higher production, but it is the opposite of PAE<Y.",
    "Although inventories rise, firms respond to unsold output by cutting rather than raising production.",
  ],
  "mix-008": [
    "This divides the autonomous investment change by the multiplier instead of applying the multiplier.",
    "This is only the first-round spending change and omits induced consumption rounds.",
    "This uses an incomplete multiplier and understates the total equilibrium effect.",
    "With MPC .75, k=1/(1-.75)=4, so a $20 autonomous increase raises equilibrium GDP by $80.",
  ],
  "mix-009": [
    "This is not the government-spending multiplier for the stated proportional-tax model.",
    "This omits the consumption response and tax leakage that determine the denominator.",
    "The correct denominator is 1-.8(1-.25)=.4, so k_G=1/.4=2.5.",
    "5 is the no-tax two-sector multiplier 1/(1-.8); proportional taxes reduce the multiplier here.",
  ],
  "mix-010": [
    "A rise in G has a positive initial demand effect, and the equal tax rise reduces consumption only through MPC, so GDP need not be unchanged.",
    "The government-spending effect is larger than the tax effect in this model, so GDP does not generally fall.",
    "A multiplier of exactly one is the special no-proportional-tax result; with t>0 the balanced-budget multiplier is generally below one.",
    "GDP rises, but proportional taxes change the leakage; the balanced-budget multiplier is not generally exactly one.",
  ],
  "mix-011": [
    "When growth exceeds the real interest rate, the GDP denominator grows faster than debt interest pressure, holding the primary balance at zero.",
    "If r exceeds g, existing debt compounds faster than the GDP denominator, so the debt ratio tends to rise.",
    "A primary surplus would reduce the ratio further rather than create the stated upward pressure.",
    "Both faster growth and a primary surplus push against, rather than cause, a rising debt ratio.",
  ],
  "mix-012": [
    "Lower market rates make the bond’s fixed future payment less heavily discounted, increasing its present market value.",
    "This reverses the inverse price-yield relationship for an existing fixed-payment bond.",
    "The market price changes even though the contractual future payment does not.",
    "The bond need not trade exactly at face value; its price depends on the new market yield and remaining payments.",
  ],
  "mix-013": [
    "A higher interest rate changes the quantity demanded along the existing money-demand curve rather than shifting the curve.",
    "Higher real income raises transaction demand at each interest rate, shifting real money demand right.",
    "A higher price level changes nominal units; with Y and i fixed, real demand MD/P is not shifted by P alone.",
    "This describes a movement along the curve, not a rightward shift caused by higher income.",
  ],
  "mix-014": [
    "The new loan is an asset for the bank and the credited deposit is a liability; the deposit does not fall at creation.",
    "Loan creation raises the bank’s loan asset and deposit liability by the same amount, increasing the money stock.",
    "Reserves may matter for settlement later, but the immediate accounting entry includes a new deposit as well as a loan.",
    "Bank equity is not the immediate counterpart of the new loan; the immediate counterpart is the borrower’s deposit liability.",
  ],
  "mix-015": [
    "Real output growth is not inflation; it is the real component of nominal spending growth.",
    "With constant velocity, g_M≈π+g_Y, so π≈7%-2%=5%.",
    "This treats all money growth as price growth and ignores the 2% real-output increase.",
    "Adding money and output growth reverses the quantity-equation rearrangement.",
  ],
  "mix-016": [
    "An RBA purchase pays banks and injects ES balances rather than draining them.",
    "Selling securities to banks makes them pay ES balances to the RBA, directly draining settlement liquidity.",
    "A private-bank transfer redistributes ES balances and leaves the system total unchanged.",
    "A government payment can add ES balances in this setup, but it is not the described draining sale.",
  ],
  "mix-017": [
    "Both positive inflation and a positive output gap call for a higher policy rate in the stated stabilisation rule.",
    "A rate cut would reinforce rather than offset the inflationary and above-potential pressures.",
    "The rule responds to gaps; it does not keep the rate fixed by definition.",
    "The policy rate is not mechanically set equal to the inflation rate.",
  ],
  "mix-018": [
    "A fall in exports is an autonomous-spending change, not a change in inflation along a fixed curve.",
    "The same autonomous-spending fall does not move the economy along the unchanged AD schedule.",
    "Lower exports reduce demand, so the AD curve shifts left rather than right.",
    "Exports enter autonomous demand; reducing them shifts AD left at each inflation rate.",
  ],
  "mix-019": [
    "A positive demand shock normally raises output and inflation, not lowers output while raising inflation.",
    "A negative demand shock normally lowers both output and inflation pressure.",
    "An input-cost increase is an adverse supply shock: inflation rises while output weakens, creating a policy trade-off.",
    "A rise in potential output is a favourable supply-side change and does not describe simultaneous higher inflation and lower output.",
  ],
  "mix-020": [
    "With unchanged potential output, a persistent demand shock cannot keep real output above Y* without continuing inflation pressure.",
    "The positive gap first raises inflation; adjustment returns output to Y* at a higher inflation rate if the demand shift persists.",
    "A persistent positive demand shock does not by itself lower output below potential.",
    "Potential output is unchanged by the demand shock in the question, so Y* does not permanently rise.",
  ],
  "mix-021": [
    "Adding S and I is not the current-account identity and gives the wrong magnitude.",
    "I-S is the opposite sign from CA=S-I, so it describes a surplus rather than the deficit.",
    "CA=S-I=100-130=-30, so the economy has a current-account deficit.",
    "This adds rather than subtracts saving and investment and has no interpretation as the current account here.",
  ],
  "mix-022": [
    "That is the closed-economy crowding-out mechanism; in the small-open model r is pinned by r*.",
    "Lower saving with unchanged investment tends to reduce, not increase, the current account.",
    "With r fixed, foreign saving finances the gap, so the current account moves toward deficit.",
    "Domestic investment need not immediately equal the lower national saving in the open economy; the difference is financed externally.",
  ],
  "mix-023": [
    "Under USD/AUD, the higher number means one AUD buys more USD, which is an appreciation.",
    "Depreciation under this quote would be a fall in the USD value of one AUD.",
    "An exchange-rate movement is not itself a statement about the inflation rate.",
    "The units identify the direction, so the change is determinate under the stated quote.",
  ],
  "mix-024": [
    "Importing households demand foreign currency and therefore supply AUD, not demand more AUD.",
    "The direction of the AUD demand shift is reversed, and the stated depreciation mechanism is incomplete.",
    "Australians sell AUD to buy foreign currency for imports, shifting AUD supply right and causing depreciation.",
    "Import payments increase rather than reduce the supply of AUD in this bilateral FX diagram.",
  ],
  "mix-025": [
    "Selling domestic currency would add to the excess supply and worsen support for an overvalued peg.",
    "Buying AUD absorbs excess private supply; paying with foreign reserves is the intervention that defends the overvalued peg.",
    "The central bank does not need to buy both currencies; it exchanges foreign reserves for domestic currency.",
    "A fixed rate requires intervention when market pressure creates excess supply or demand.",
  ],
  "mix-026": [
    "The input contribution is not zero because capital and labour growth are positive.",
    "TFP is the residual: 4 - [.5(4)+.5(2)] = 4 - 3 = 1%.",
    "This subtracts the unweighted input total or otherwise overstates the residual.",
    "Three percentage points is the weighted input contribution, not the TFP residual.",
  ],
  "mix-027": [
    "The capital exponent does not mean output rises by only 30% when both inputs scale together.",
    "The labour exponent alone is not the relevant scaling result because both K and L double.",
    "Because the exponents sum to one, 2^0.3×2^0.7=2, so output doubles.",
    "Quadrupling would require a different returns-to-scale result; constant returns gives a twofold output change.",
  ],
  "mix-028": [
    "Capital’s marginal product is positive in the standard model; diminishing returns does not make it negative.",
    "Population growth is not the mechanism in the stated production model, and it does not explain diminishing returns to capital per worker.",
    "Each additional unit of capital per worker adds less output than the previous one, limiting capital-only sustained growth.",
    "The model permits saving and investment; openness does not eliminate capital accumulation.",
  ],
  "mix-029": [
    "These pairings swap the equilibrium concepts and introduce conditions not belonging to the named models.",
    "Income-expenditure uses Y=PAE; closed saving-investment uses S=I; long-run AD-AS uses Y=Y*.",
    "These equations belong to different model closures, not the pairings shown.",
    "The models do not require nominal GDP and real GDP to be numerically equal; prices and quantities are distinct.",
  ],
  "mix-030": [
    "The first step reverses the PRF effect, so the spending and AD directions do not follow.",
    "This starts with the wrong PRF shift and therefore cannot describe contractionary policy.",
    "An upward PRF shift raises r at each inflation rate, lowering C and I and shifting AD left.",
    "Higher r lowers interest-sensitive spending; it does not raise C and I in this course model.",
  ],
};
