import { c, L, T } from "./records";

export const courseRecordsA = [
  c({
    id: "gross-domestic-product",
    name: "Gross domestic product (GDP)",
    aliases: ["GDP", "gross domestic product"],
    searchTerms: ["total production", "size of the economy", "national output"],
    chapters: [1],
    tags: ["chapter-1", "output", "high-yield"],
    summary:
      "GDP is the market value of final goods and services produced within a country during a period.",
    intuition:
      "GDP is a carefully defined scoreboard for current domestic production: it adds unlike goods using prices, counts final output once, and states a location and time window.",
    explanation: [
      "The word domestic refers to where production occurs, not who owns the producer. The word gross means production is measured before subtracting depreciation of capital goods.",
      "GDP can be measured by production/value added, expenditure on final output, or income generated by production. These are accounting views of the same current activity.",
      "GDP is a flow, so an annual GDP number records production during the year. It is not the stock of wealth owned at the end of the year.",
    ],
    whyItMatters:
      "GDP is the course’s central measure of output and enters the labour, expenditure, fiscal, AD-AS, international, and growth models.",
    prerequisites: ["price", "quantity", "final-good", "flow"],
    relatedConcepts: [
      "value-added",
      "expenditure-approach",
      "nominal-gdp",
      "real-gdp",
      "gdp-vs-gni",
      "gdp-welfare",
    ],
    mechanism: [
      "identify current domestic production",
      "value final goods and services at market prices",
      "add production once, using final sales or value added",
      "report the resulting flow for the chosen period",
    ],
    examples: [
      {
        title: "Australian production",
        text: "A car assembled in Australia contributes to Australian GDP even if the car company is foreign-owned; an Australian household’s imported laptop is offset by imports because production occurred overseas.",
        takeaway:
          "GDP follows the location of production, not the nationality of the buyer or owner.",
      },
    ],
    equations: [
      {
        label: "Expenditure identity",
        expression: "Y = C + I + G + X − M",
        variables: [
          { symbol: "Y", meaning: "GDP or aggregate output" },
          { symbol: "C", meaning: "household consumption expenditure" },
          { symbol: "I", meaning: "macroeconomic investment" },
          { symbol: "G", meaning: "government purchases" },
          { symbol: "X", meaning: "exports" },
          { symbol: "M", meaning: "imports" },
        ],
        interpretation:
          "Imports are subtracted because spending on foreign production is not domestic production.",
      },
    ],
    misconceptions: [
      "GDP is not every transaction, every purchase, or a complete measure of wellbeing.",
      "A second-hand sale is not new production, although the seller’s current service can be included.",
      "Investment in GDP does not mean buying shares; it means newly produced capital goods, inventories, or new dwellings.",
    ],
    sourceRefs: [
      L("lecture-w1-l1", 23, "Lecture definition and components of GDP."),
      T(18, "Textbook definition and exclusions from GDP."),
    ],
  }),
  c({
    id: "final-good",
    name: "Final good or service",
    aliases: ["final goods", "final output"],
    searchTerms: ["finished product", "not an intermediate input"],
    chapters: [1],
    tags: ["chapter-1", "output"],
    summary:
      "A final good or service is counted as an end product rather than an input used up in another current product.",
    intuition:
      "The final label is about the role of the purchase in production, not whether the object is physically large or durable.",
    explanation: [
      "Counting a final product and all the inputs used to make it would count the same production more than once. National accounts avoid that by counting final sales or adding value added.",
      "The same item can be an intermediate input for one buyer and a final purchase for another, depending on its use.",
    ],
    whyItMatters:
      "Final-versus-intermediate classification is a recurring GDP definition and calculation trap.",
    prerequisites: ["market"],
    relatedConcepts: ["intermediate-good", "value-added", "expenditure-approach"],
    sourceRefs: [
      L("lecture-w1-l1", 37, "Lecture examples of final and intermediate goods."),
      T(20, "Value-added example for a hamburger."),
    ],
    contrasts: [
      {
        conceptId: "intermediate-good",
        title: "Final versus intermediate",
        difference:
          "A final good is counted as end output; an intermediate good is used up in making another current product.",
      },
    ],
  }),
  c({
    id: "intermediate-good",
    name: "Intermediate good",
    aliases: ["intermediate goods", "intermediate input", "input"],
    searchTerms: ["business input", "good used in another product"],
    chapters: [1],
    tags: ["chapter-1", "output"],
    summary:
      "An intermediate good or service is used up in producing another current good or service.",
    intuition:
      "Flour sold to a bakery is part of the bread’s production chain; counting both flour and the bread at full value would double count the same chain.",
    explanation: [
      "Intermediate status depends on use. A computer purchased by a firm for production can be an input, while a computer purchased by a household is final consumption in the GDP accounts.",
      "The value of intermediate inputs is captured indirectly through the final product or directly through each firm’s value added.",
    ],
    whyItMatters:
      "It explains why GDP is not the sum of every firm’s sales and why value added prevents double counting.",
    prerequisites: ["final-good", "flow"],
    relatedConcepts: ["value-added", "gross-domestic-product", "macro-investment"],
    sourceRefs: [
      L("lecture-w1-l1", 40, "Lecture definition of intermediate inputs."),
      T(20, "Textbook value-added table."),
    ],
  }),
  c({
    id: "value-added",
    name: "Value added",
    aliases: ["value-added approach", "value added"],
    searchTerms: ["sales minus intermediate inputs", "firm contribution to GDP"],
    chapters: [1],
    tags: ["chapter-1", "output", "calculation"],
    summary:
      "Value added is a firm’s sales value minus the value of intermediate inputs it bought from other firms.",
    intuition:
      "It measures what the firm added to the production chain rather than counting the full value of inputs that were already produced elsewhere.",
    explanation: [
      "Adding every firm’s value added gives the value of final production. Wages, profits, and taxes on production are ways that the value created is distributed as income.",
      "A firm can have high sales but low value added if most of its sales value is purchased inputs.",
    ],
    whyItMatters:
      "Value added is the production method for GDP and the cleanest response to double-counting questions.",
    prerequisites: ["intermediate-good", "gross-domestic-product", "expenditure"],
    relatedConcepts: ["income-approach", "expenditure-approach", "final-good"],
    sourceRefs: [
      L("lecture-w1-l1", 42, "Value Added for Computer Sales."),
      T(20, "Value-added example in Chapter 1."),
    ],
    equations: [
      {
        label: "Firm value added",
        expression: "sales − intermediate-input cost",
        variables: [
          { symbol: "sales", meaning: "value of the firm’s output" },
          {
            symbol: "intermediate-input cost",
            meaning: "value of inputs bought from other firms",
          },
        ],
        interpretation:
          "Summing this across firms counts each stage of production once without double counting inputs.",
      },
    ],
  }),
  c({
    id: "expenditure-approach",
    name: "Expenditure approach to GDP",
    aliases: ["expenditure method", "GDP expenditure method"],
    searchTerms: ["C plus I plus G plus X minus M", "spending approach"],
    chapters: [1],
    tags: ["chapter-1", "accounting", "calculation"],
    summary:
      "The expenditure approach adds spending on final domestic output by households, firms, government, and foreigners.",
    intuition:
      "Instead of asking who produced the output, ask who bought the final goods and services, then remove spending that paid for foreign production.",
    explanation: [
      "Consumption is household spending, investment is firms’ and households’ purchases of new capital and inventories, and government spending is government purchases of goods and services.",
      "Exports add foreign spending on domestic production. Imports are subtracted because they can be included in C, I, or G even though they were produced abroad.",
    ],
    whyItMatters:
      "It turns GDP questions into classification and sign discipline: C, I, G, X, and M are not interchangeable labels.",
    prerequisites: [
      "gross-domestic-product",
      "expenditure",
      "consumption",
      "macro-investment",
      "government-spending",
      "net-exports",
    ],
    relatedConcepts: [
      "income-approach",
      "planned-aggregate-expenditure",
      "gross-domestic-product",
    ],
    sourceRefs: [
      L("lecture-w1-l1", 49, "Expenditure method and component definitions."),
      T(22, "GDP expenditure approach and tables."),
    ],
  }),
  c({
    id: "income-approach",
    name: "Income approach to GDP",
    aliases: ["income method", "GDP income method"],
    searchTerms: ["income generated by production", "wages profits and taxes"],
    chapters: [1],
    tags: ["chapter-1", "accounting"],
    summary:
      "The income approach measures GDP by adding the incomes generated in producing output.",
    intuition:
      "Every sale of current output creates revenue that is paid to workers, owners of capital, or government through production-related taxes.",
    explanation: [
      "In the course’s simplified identity, GDP equals labour income plus capital income plus net indirect taxes. It is another accounting view of the same production measured by the expenditure approach.",
      "This is not a measure of household take-home pay: taxes, transfers, and saving determine how production income is distributed and spent.",
    ],
    whyItMatters:
      "It links output to income and helps explain why income, expenditure, and production identities coincide.",
    prerequisites: ["gross-domestic-product", "income", "value-added"],
    relatedConcepts: ["expenditure-approach", "income", "capital", "wage"],
    sourceRefs: [
      L("lecture-w1-l1", 53, "GDP as aggregate incomes paid to factors."),
      T(26, "Income approach table."),
    ],
  }),
  c({
    id: "consumption",
    name: "Consumption",
    aliases: ["consumption expenditure", "household consumption", "C"],
    searchTerms: ["household spending", "purchases by households"],
    chapters: [1, 4],
    tags: ["chapter-1", "chapter-4", "spending"],
    summary:
      "Consumption is household expenditure on currently used goods and services.",
    intuition:
      "A household consumes when it uses a good or service for current satisfaction; buying a share or a new machine is classified differently in the macro accounts.",
    explanation: [
      "Consumption is one component of expenditure GDP and planned aggregate expenditure. It responds to disposable income and, in the later model, to the real interest rate and other influences.",
      "Durability alone does not make a purchase macroeconomic investment. A household laptop can be consumption even though it lasts for years.",
    ],
    whyItMatters:
      "Consumption is usually the largest spending component and drives the multiplier through the marginal propensity to consume.",
    prerequisites: ["income", "expenditure", "final-good"],
    relatedConcepts: [
      "macro-investment",
      "disposable-income",
      "consumption-function",
      "planned-aggregate-expenditure",
    ],
    sourceRefs: [
      L("lecture-w1-l1", 50, "GDP expenditure components."),
      L("lecture-w3-l1", 31, "Consumption in the two-sector PAE model."),
      T(121, "Consumption function."),
    ],
    misconceptions: [
      "Consumption is not every household purchase: buying a newly built dwelling is treated as investment in the national accounts.",
    ],
  }),
  c({
    id: "capital",
    name: "Capital",
    aliases: ["capital goods", "productive capital", "K"],
    searchTerms: ["machines and structures used to produce", "productive equipment"],
    chapters: [0, 3, 10],
    tags: ["foundation", "chapter-3", "chapter-10", "growth"],
    summary: "Capital is a produced resource used to make other goods and services.",
    intuition:
      "A machine, building, or software system helps workers produce in the future; it is a tool in the production process, not just money.",
    explanation: [
      "Capital is a stock: an economy has a quantity of productive capital at a point in time. Investment is the flow of new capital goods purchased during a period.",
      "Capital can depreciate as it wears out or becomes obsolete. Human, natural, and social capital are related growth concepts but are not interchangeable with a firm’s physical capital stock.",
    ],
    whyItMatters:
      "Capital connects the GDP investment category to productivity, capital accumulation, user cost, and long-run growth.",
    prerequisites: ["asset", "stock"],
    relatedConcepts: [
      "macro-investment",
      "capital-stock",
      "capital-accumulation",
      "productivity",
    ],
    sourceRefs: [
      L("lecture-w2-l2", 3, "Investment is a flow and capital is a stock."),
      T(84, "Investment and capital stock in Chapter 3."),
    ],
  }),
  c({
    id: "macro-investment",
    name: "Macroeconomic investment",
    aliases: ["investment", "investment expenditure", "I"],
    searchTerms: ["new capital spending", "business investment", "investment in GDP"],
    chapters: [1, 3, 4, 9],
    tags: ["chapter-1", "chapter-3", "chapter-4", "high-yield"],
    summary:
      "Macroeconomic investment is spending on newly produced capital goods, inventories, and new dwellings.",
    intuition:
      "Investment adds to productive capacity or records goods being held for later sale; it is a flow that changes capital or inventories.",
    explanation: [
      "Business purchases of plant and equipment, construction of new dwellings, and changes in inventories are investment in the national accounts.",
      "Buying an existing share, bond, or second-hand house transfers ownership of an existing asset. It may finance investment, but the financial purchase itself is not GDP investment.",
      "Investment is chosen by comparing the expected value of productive capital with its user cost, which includes the real interest rate and depreciation.",
    ],
    whyItMatters:
      "It appears in GDP, PAE, saving-investment equilibrium, the real-rate channel, and long-run capital accumulation.",
    prerequisites: ["capital", "flow", "expenditure", "present-value"],
    relatedConcepts: [
      "capital-stock",
      "investment-demand",
      "inventory-investment",
      "saving",
      "financial-asset",
    ],
    sourceRefs: [
      L("lecture-w1-l1", 50, "Investment as a GDP expenditure component."),
      L("lecture-w2-l2", 2, "Definition of investment as new capital goods."),
      T(84, "Investment and capital stock."),
    ],
    misconceptions: [
      "Investment in macroeconomics usually does not mean buying shares or bonds; those are financial assets.",
      "Saving and investment are related by accounting, but a household’s decision to save is not the same action as a firm’s decision to buy capital.",
    ],
  }),
  c({
    id: "government-spending",
    name: "Government spending",
    aliases: ["government purchases", "government expenditure", "G"],
    searchTerms: ["public purchases", "government demand for goods and services"],
    chapters: [1, 4, 5],
    tags: ["chapter-1", "chapter-5", "fiscal"],
    summary:
      "Government spending in GDP is government purchases of currently produced goods and services.",
    intuition:
      "A public hospital’s wages and a government-built bridge are purchases of current production; a transfer payment changes recipients’ income but is not itself a purchase of output.",
    explanation: [
      "Government spending is an exogenous or policy-controlled component in the basic PAE model. Taxes and transfers affect disposable income and therefore consumption, but they enter the accounting model differently.",
      "A budget deficit is not the same thing as government spending: it is the gap between government spending and revenue over a period.",
    ],
    whyItMatters:
      "The government sector changes the multiplier, output gap, budget balance, and debt dynamics.",
    prerequisites: ["expenditure", "income", "flow"],
    relatedConcepts: [
      "fiscal-policy",
      "budget-balance",
      "government-spending-multiplier",
      "automatic-stabilisers",
    ],
    sourceRefs: [
      L("lecture-w1-l1", 50, "Government purchases in expenditure GDP."),
      T(140, "Government expenditure in the fiscal-policy chapter."),
    ],
  }),
  c({
    id: "imports",
    name: "Imports",
    aliases: ["imports", "M"],
    searchTerms: [
      "goods produced overseas and bought domestically",
      "foreign production purchased",
    ],
    chapters: [1, 4, 9],
    tags: ["chapter-1", "chapter-4", "international"],
    summary:
      "Imports are goods and services produced abroad and purchased by domestic residents.",
    intuition:
      "An imported phone can be part of household spending, but it is not domestic production, so GDP accounting subtracts its value as imports.",
    explanation: [
      "Imports can appear inside C, I, or G depending on who buys them. Subtracting M removes the foreign-produced part from domestic expenditure.",
      "In the open-economy PAE model, imports are also a leakage: as income rises, some extra spending flows abroad rather than creating domestic demand.",
    ],
    whyItMatters:
      "Imports explain both the sign in the GDP identity and why an open economy has a smaller multiplier than a closed economy.",
    prerequisites: ["gross-domestic-product", "expenditure", "market"],
    relatedConcepts: ["exports", "net-exports", "open-economy-pae", "trade-balance"],
    sourceRefs: [
      L("lecture-w1-l1", 50, "Net exports in the expenditure identity."),
      L("lecture-w3-l2", 46, "Imports as a leakage from domestic PAE."),
      T(134, "Open-economy multiplier."),
    ],
  }),
  c({
    id: "exports",
    name: "Exports",
    aliases: ["exports", "X"],
    searchTerms: [
      "domestic production bought by foreigners",
      "foreign demand for local output",
    ],
    chapters: [1, 4, 9],
    tags: ["chapter-1", "chapter-4", "international"],
    summary:
      "Exports are domestically produced goods and services purchased by foreign residents.",
    intuition:
      "Exports add to domestic production even though the final buyer lives elsewhere.",
    explanation: [
      "Exports are added to expenditure GDP because foreign spending is a source of demand for domestic output. Net exports are exports minus imports.",
      "A rise in exports can raise domestic aggregate demand, but the final effect depends on the model and any induced imports.",
    ],
    whyItMatters:
      "Exports connect domestic output to foreign demand, net exports, the AUD market, and open-economy shocks.",
    prerequisites: ["gross-domestic-product", "expenditure", "market"],
    relatedConcepts: ["imports", "net-exports", "aggregate-demand", "trade-balance"],
    sourceRefs: [
      L("lecture-w1-l1", 50, "Exports in the expenditure identity."),
      L("lecture-w8-l1", 8, "Australian current-account components include exports."),
      T(247, "Balance-of-payments transaction classification."),
    ],
  }),
  c({
    id: "net-exports",
    name: "Net exports",
    aliases: ["net exports", "NX", "exports minus imports"],
    searchTerms: ["trade balance", "foreign sales less foreign purchases"],
    chapters: [1, 4, 9],
    tags: ["chapter-1", "chapter-4", "international", "calculation"],
    summary: "Net exports are exports minus imports.",
    intuition:
      "Net exports measure whether foreign demand for domestic output exceeds domestic demand for foreign output.",
    explanation: [
      "Positive net exports mean exports exceed imports; negative net exports mean imports exceed exports. The sign is about flows of current goods and services, not necessarily financial wealth.",
      "Net exports are part of GDP expenditure and planned aggregate expenditure. In the balance of payments, the trade balance is a major current-account component.",
    ],
    whyItMatters:
      "Net exports are a key leakage/injection term and a frequent source of sign errors in open-economy questions.",
    prerequisites: ["exports", "imports", "flow"],
    relatedConcepts: [
      "trade-balance",
      "current-account",
      "open-economy-pae",
      "real-exchange-rate",
    ],
    sourceRefs: [
      L("lecture-w1-l1", 50, "Net exports in GDP expenditure."),
      L("lecture-w8-l1", 50, "Saving, investment, and net exports."),
      T(249, "Open-economy saving and investment."),
    ],
    equations: [
      {
        label: "Net exports",
        expression: "NX = X − M",
        variables: [
          { symbol: "X", meaning: "exports of domestic output" },
          { symbol: "M", meaning: "imports of foreign output" },
        ],
        interpretation:
          "A negative NX is a trade deficit; it does not mean GDP accounting omitted imports.",
      },
    ],
  }),
  c({
    id: "nominal-gdp",
    name: "Nominal GDP",
    aliases: ["nominal GDP", "GDP at current prices"],
    searchTerms: ["current-price GDP", "dollar value of output"],
    chapters: [1],
    tags: ["chapter-1", "measurement"],
    summary: "Nominal GDP values current production using current-period prices.",
    intuition:
      "Nominal GDP is the dollar total you would get from adding this period’s quantities at this period’s price tags.",
    explanation: [
      "If nominal GDP rises, you cannot tell from that fact alone whether more was produced or prices rose. Real GDP is designed to focus on production quantities.",
      "Nominal GDP and the GDP price index combine multiplicatively in the course’s simplified relationship.",
    ],
    whyItMatters:
      "It is the starting point for the nominal-versus-real GDP distinction and the GDP deflator.",
    prerequisites: ["gross-domestic-product", "nominal", "price", "quantity"],
    relatedConcepts: ["real-gdp", "gdp-deflator", "gdp-growth", "price-level"],
    sourceRefs: [
      L("lecture-w1-l1", 61, "Nominal GDP and the reason for real GDP."),
      T(29, "Nominal and real GDP table."),
    ],
  }),
  c({
    id: "real-gdp",
    name: "Real GDP",
    aliases: ["real GDP", "chain-volume GDP", "constant-price GDP"],
    searchTerms: ["inflation-adjusted output", "volume of production", "real output"],
    chapters: [1, 2, 8, 10],
    tags: ["chapter-1", "output", "high-yield"],
    summary:
      "Real GDP measures production using a price method intended to remove the effect of changing prices.",
    intuition:
      "It is a common-price ruler for output: the economy can look larger because it made more things, not merely because the price labels changed.",
    explanation: [
      "The lectures compare quantities at base-year prices and then introduce chain-weighted real GDP. The exact index construction can vary, but the purpose is the same: track changes in production volume.",
      "Real GDP growth is the percentage change in real GDP. Real GDP per capita divides real GDP by population and is used as an indicator of material living standards, with important limitations.",
    ],
    whyItMatters:
      "Real GDP is the output variable in the business-cycle, labour, AD-AS, and growth parts of the course.",
    prerequisites: ["nominal-gdp", "real", "price-index", "quantity"],
    relatedConcepts: [
      "nominal-gdp",
      "gdp-deflator",
      "gdp-growth",
      "potential-output",
      "gdp-per-capita",
    ],
    mechanism: [
      "choose a price-weighting method",
      "value current quantities using that method",
      "compare real GDP across periods to infer output growth",
    ],
    equations: [
      {
        label: "Simplified GDP decomposition",
        expression: "nominal GDP = price level × real GDP",
        variables: [
          { symbol: "nominal GDP", meaning: "current-price dollar value" },
          { symbol: "price level", meaning: "GDP price index in the model" },
          { symbol: "real GDP", meaning: "price-adjusted output measure" },
        ],
        interpretation:
          "A nominal increase can be decomposed approximately into price growth and real-output growth.",
      },
    ],
    misconceptions: [
      "Real GDP is not GDP measured in a different currency; it is a price-adjusted measure of domestic production.",
      "Real GDP growth is not the same as nominal GDP growth when prices are changing.",
    ],
    sourceRefs: [
      L("lecture-w1-l1", 62, "Base-year and chain-weighted real GDP."),
      T(29, "Nominal and real GDP calculations."),
    ],
  }),
  c({
    id: "gdp-deflator",
    name: "GDP deflator",
    aliases: ["GDP price index", "GDP deflator or price index"],
    searchTerms: ["price index for domestic output", "nominal GDP divided by real GDP"],
    chapters: [1],
    tags: ["chapter-1", "measurement", "calculation"],
    summary:
      "The GDP deflator is a price index for goods and services included in domestic GDP.",
    intuition:
      "It asks how expensive the current bundle of domestic production is relative to its real-output valuation.",
    explanation: [
      "In the simplified course relationship, the deflator is nominal GDP divided by real GDP, often scaled to a base of 100.",
      "Unlike CPI, the GDP deflator covers domestically produced final output and does not use a fixed household-consumption basket in the same way.",
    ],
    whyItMatters:
      "GDP-deflator questions test whether you understand which basket or production set an index measures.",
    prerequisites: ["nominal-gdp", "real-gdp", "price-index"],
    relatedConcepts: ["cpi", "inflation", "price-level", "nominal", "real"],
    sourceRefs: [
      L(
        "lecture-w1-l2",
        2,
        "Measures of the aggregate price level and the GDP deflator.",
      ),
      T(31, "GDP price index table."),
    ],
    equations: [
      {
        label: "GDP deflator",
        expression: "nominal GDP / real GDP",
        variables: [
          { symbol: "nominal GDP", meaning: "current-price output value" },
          { symbol: "real GDP", meaning: "price-adjusted output value" },
        ],
        interpretation:
          "A change in the deflator signals a change in prices represented in domestic output, not necessarily household living costs.",
      },
    ],
    contrasts: [
      {
        conceptId: "cpi",
        title: "GDP deflator versus CPI",
        difference:
          "The GDP deflator covers domestic production; CPI tracks the cost of a household-consumption basket, including imports.",
      },
    ],
  }),
  c({
    id: "price-level",
    name: "Price level",
    aliases: ["general price level", "overall price level"],
    searchTerms: [
      "average level of prices",
      "how expensive the economy-wide basket is",
    ],
    chapters: [1, 8],
    tags: ["chapter-1", "chapter-8", "prices"],
    summary:
      "The price level is an index-like summary of prices across a defined collection of goods and services.",
    intuition:
      "It is the height of the price landscape, not the speed at which that landscape is rising.",
    explanation: [
      "A price level is measured with an index such as CPI or the GDP deflator. The index’s base is a reference convention.",
      "Inflation is the percentage change in a price level. Prices can remain high while inflation falls, because a lower rate of increase is not a fall in the level.",
    ],
    whyItMatters:
      "The price-level versus inflation-rate distinction is one of the course’s most important beginner traps.",
    prerequisites: ["price-index", "percentage-change"],
    relatedConcepts: ["inflation", "disinflation", "cpi", "gdp-deflator"],
    sourceRefs: [
      L(
        "lecture-w1-l2",
        2,
        "The lecture distinguishes aggregate prices and inflation.",
      ),
      T(39, "Price-index construction."),
    ],
    misconceptions: [
      "A fall in inflation means prices are rising more slowly; it does not by itself mean the price level is falling.",
    ],
  }),
  c({
    id: "cpi",
    name: "Consumer price index (CPI)",
    aliases: ["CPI", "consumer price index", "cost-of-living index"],
    searchTerms: ["household basket", "cost of living measure", "consumer prices"],
    chapters: [1, 7, 9],
    tags: ["chapter-1", "prices", "high-yield"],
    summary:
      "CPI measures the cost of a specified basket of goods and services purchased by consumers relative to a base period.",
    intuition:
      "CPI follows a representative shopping basket: if the same basket becomes more expensive, CPI rises.",
    explanation: [
      "Constructing CPI requires a basket, prices, quantities or weights, and a base period. The result is an index, not an amount of output.",
      "CPI can include imported consumer goods because households buy them. Its coverage and weights differ from the GDP deflator, which follows domestic production.",
      "The course notes bias from quality changes, new goods, and substitution: the index is useful but not a perfect individual cost-of-living measure.",
    ],
    whyItMatters:
      "CPI supplies the course’s inflation measure and is used to convert nominal interest into real purchasing-power terms.",
    prerequisites: ["price-index", "price", "quantity", "consumption"],
    relatedConcepts: ["inflation", "gdp-deflator", "price-level", "real-interest-rate"],
    sourceRefs: [
      L("lecture-w1-l2", 4, "CPI basket construction."),
      T(39, "Consumer price index construction and limitations."),
    ],
    misconceptions: [
      "CPI is not GDP: it tracks a consumer basket, not all domestically produced final output.",
      "A CPI index of 120 does not mean inflation is currently 120%; it means the basket is 20% above the base-period level.",
    ],
  }),
  c({
    id: "inflation",
    name: "Inflation",
    aliases: ["inflation rate", "π", "rising prices"],
    searchTerms: [
      "prices going up",
      "rate at which prices rise",
      "cost of living rising",
    ],
    chapters: [1, 3, 7, 8, 9],
    tags: ["chapter-1", "prices", "high-yield"],
    summary: "Inflation is the percentage change in a price index over time.",
    intuition:
      "Inflation is the speed at which the general price level changes, not the height of the price level itself.",
    explanation: [
      "If CPI rises from 100 to 103, the inflation rate is approximately 3%, not 103%. The denominator is the earlier index value.",
      "Inflation can be anticipated or unexpected. It changes the purchasing power of money and affects the gap between nominal and real interest rates.",
      "The course discusses costs of high or variable inflation, but a small positive target can help avoid deflation and provide room for real-rate adjustment.",
    ],
    whyItMatters:
      "Inflation appears in CPI calculations, Fisher relationships, the RBA target, AD-AS dynamics, PPP, and policy rules.",
    prerequisites: ["price-level", "percentage-change", "price-index"],
    relatedConcepts: [
      "cpi",
      "deflation",
      "disinflation",
      "nominal-interest-rate",
      "real-interest-rate",
      "inflation-target",
    ],
    mechanism: [
      "measure a price index in two periods",
      "calculate the percentage change",
      "interpret a positive, zero, or negative rate as inflation, stable prices, or deflation",
    ],
    equations: [
      {
        label: "Inflation from a price index",
        expression: "πₜ = (Pₜ − Pₜ₋₁) / Pₜ₋₁",
        variables: [
          { symbol: "πₜ", meaning: "inflation rate over the period" },
          { symbol: "Pₜ", meaning: "current price index" },
          { symbol: "Pₜ₋₁", meaning: "previous price index" },
        ],
        interpretation:
          "Multiply by 100 for percent; this is a rate of change, not the index level.",
      },
    ],
    misconceptions: [
      "Disinflation is lower positive inflation, not necessarily falling prices.",
      "A rise in one relative price is not automatically economy-wide inflation.",
    ],
    sourceRefs: [
      L("lecture-w1-l2", 10, "Inflation as percentage change in CPI."),
      T(40, "Inflation definition and costs."),
    ],
  }),
  c({
    id: "deflation",
    name: "Deflation",
    aliases: ["deflation rate", "falling price level"],
    searchTerms: ["prices falling", "negative inflation"],
    chapters: [1],
    tags: ["chapter-1", "prices", "contrast"],
    summary:
      "Deflation is a sustained fall in the general price level, meaning a negative inflation rate.",
    intuition: "The index itself is moving down, not merely rising more slowly.",
    explanation: [
      "Deflation can result from favourable supply conditions or weak demand. Its effects depend on expectations, debts, wages, and why prices fell.",
      "A lower inflation rate is not deflation unless the inflation rate becomes negative.",
    ],
    whyItMatters:
      "The course contrasts good and bad deflation and asks you to distinguish it from disinflation.",
    prerequisites: ["inflation", "price-level"],
    relatedConcepts: ["disinflation", "inflation", "demand-shock", "supply-shock"],
    sourceRefs: [
      L("lecture-w1-l2", 10, "Inflation and deflation definition."),
      T(40, "Inflation and deflation discussion."),
    ],
    contrasts: [
      {
        conceptId: "disinflation",
        title: "Deflation versus disinflation",
        difference:
          "Deflation is a falling price level; disinflation is a falling inflation rate that can remain positive.",
      },
    ],
  }),
  c({
    id: "disinflation",
    name: "Disinflation",
    aliases: ["slowing inflation", "fall in inflation"],
    searchTerms: [
      "prices still rising more slowly",
      "inflation falls but stays positive",
    ],
    chapters: [1],
    tags: ["chapter-1", "prices", "contrast"],
    summary:
      "Disinflation is a decline in the inflation rate, often while the price level continues to rise.",
    intuition:
      "The price level is still climbing, but the climb is less steep than before.",
    explanation: [
      "If inflation falls from 6% to 3%, the price level is still increasing at 3% per period. Deflation would require the rate to fall below zero.",
      "Disinflation can reduce inflation pressure without reversing the accumulated level of prices.",
    ],
    whyItMatters:
      "It is the canonical example of why a rate of change and a level cannot be treated as the same thing.",
    prerequisites: ["inflation", "price-level", "percentage-point"],
    relatedConcepts: ["deflation", "inflation-target", "price-index"],
    sourceRefs: [
      T(40, "Inflation chapter terminology."),
      L("lecture-w1-l2", 19, "Anticipated and policy-relevant inflation changes."),
    ],
  }),
  c({
    id: "gdp-growth",
    name: "Real GDP growth",
    aliases: ["GDP growth", "economic output growth"],
    searchTerms: ["output growth", "percentage change in real GDP"],
    chapters: [1, 10],
    tags: ["chapter-1", "chapter-10", "growth"],
    summary:
      "Real GDP growth is the percentage change in inflation-adjusted output between periods.",
    intuition:
      "It tells you whether the economy produced more or less in volume terms, rather than whether its dollar receipts changed.",
    explanation: [
      "Use real GDP for growth comparisons when prices change. A positive growth rate means the real GDP level increased; a negative rate means it decreased.",
      "Short-run GDP growth and long-run economic growth use related arithmetic but answer different questions about cycles and sustained living standards.",
    ],
    whyItMatters:
      "The course uses real GDP growth to identify expansions, contractions, recessions, and long-run growth.",
    prerequisites: ["real-gdp", "growth-rate"],
    relatedConcepts: [
      "business-cycle",
      "technical-recession",
      "economic-growth",
      "gdp-per-capita",
    ],
    sourceRefs: [
      L("lecture-w1-l1", 70, "Real GDP growth calculation."),
      T(34, "Quarterly growth and business-cycle measurement."),
    ],
  }),
  c({
    id: "gdp-per-capita",
    name: "Real GDP per capita",
    aliases: ["GDP per capita", "real GDP per person", "output per person"],
    searchTerms: ["average output per person", "GDP divided by population"],
    chapters: [1, 10],
    tags: ["chapter-1", "chapter-10", "growth"],
    summary: "Real GDP per capita is real GDP divided by population.",
    intuition:
      "Total output can grow while output per person falls if population grows faster than real GDP.",
    explanation: [
      "It is a rough indicator of material resources per person, not a measure of how equally income is distributed or of all aspects of wellbeing.",
      "Its growth can be approximated by real GDP growth minus population growth.",
    ],
    whyItMatters:
      "The growth chapter uses output per person to compare living standards and productivity over time.",
    prerequisites: ["real-gdp", "ratio", "growth-rate"],
    relatedConcepts: ["economic-growth", "output-per-worker", "gdp-welfare"],
    sourceRefs: [
      L("lecture-w1-l1", 78, "Real GDP per capita definition."),
      L("lecture-w9-l1", 3, "Real GDP per capita as a growth indicator."),
      T(32, "GDP per capita and welfare."),
    ],
    equations: [
      {
        label: "Per-capita output",
        expression: "real GDP / population",
        variables: [
          { symbol: "real GDP", meaning: "inflation-adjusted domestic output" },
          { symbol: "population", meaning: "number of people" },
        ],
        interpretation:
          "It is an average, not a claim that every person receives the same output or income.",
      },
    ],
  }),
  c({
    id: "business-cycle",
    name: "Business cycle",
    aliases: ["business cycles", "economic cycle"],
    searchTerms: ["expansion and contraction", "ups and downs in output"],
    chapters: [1, 2, 8],
    tags: ["chapter-1", "chapter-8", "output"],
    summary:
      "The business cycle is the pattern of expansions and contractions in economic activity around a longer-run path.",
    intuition:
      "Actual output can move above and below what the economy could sustainably produce, creating output gaps and labour-market changes.",
    explanation: [
      "The course describes expansions as periods of rising GDP and contractions as periods of falling GDP, with recessions defined by a chosen rule such as two consecutive quarters of falling real GDP.",
      "The cycle is not simply a graph’s wiggle: its interpretation depends on real GDP, potential output, inflation, employment, and the timing of shocks.",
    ],
    whyItMatters:
      "The cycle motivates stabilisation policy and links GDP, unemployment, inflation, and AD-AS adjustment.",
    prerequisites: ["real-gdp", "gdp-growth", "potential-output"],
    relatedConcepts: [
      "technical-recession",
      "output-gap",
      "cyclical-unemployment",
      "aggregate-demand",
    ],
    sourceRefs: [
      L("lecture-w1-l1", 84, "Business-cycle expansions and contractions."),
      T(36, "Classical business-cycle discussion."),
    ],
  }),
  c({
    id: "technical-recession",
    name: "Technical recession",
    aliases: ["recession", "two-quarter recession"],
    searchTerms: ["two consecutive quarters of falling GDP", "recession rule of thumb"],
    chapters: [1, 2],
    tags: ["chapter-1", "chapter-2", "output"],
    summary:
      "In the course’s rule-of-thumb definition, a technical recession is at least two consecutive quarters of falling real GDP.",
    intuition:
      "It is a classification based on the direction of the output level across consecutive periods, not simply one bad month or output below potential.",
    explanation: [
      "A recession can also be assessed using broader indicators and professional dating; the course’s exam convention is the explicit two-quarter rule.",
      "Output can be below potential without falling, and output can fall from a high level without necessarily being below potential. Those are separate dimensions.",
    ],
    whyItMatters:
      "It tests level-versus-growth and level-versus-potential distinctions.",
    prerequisites: ["business-cycle", "real-gdp", "gdp-growth"],
    relatedConcepts: ["output-gap", "cyclical-unemployment", "potential-output"],
    sourceRefs: [
      L("lecture-w1-l1", 89, "Lecture rule-of-thumb definition of recession."),
      T(37, "Classical recession dates and discussion."),
    ],
    misconceptions: [
      "A below-potential observation alone is not the technical two-quarter recession rule.",
    ],
  }),
  c({
    id: "gdp-vs-gni",
    name: "GDP versus GNI",
    aliases: ["GDP vs GNI", "gross national income", "GNI"],
    searchTerms: [
      "domestic production versus resident income",
      "income earned by nationals",
    ],
    chapters: [1],
    tags: ["chapter-1", "accounting", "contrast"],
    summary:
      "GDP counts production inside a country; GNI counts income received by the country’s residents, including relevant cross-border income flows.",
    intuition:
      "GDP asks where production happened; GNI asks who receives the associated income after international income flows are considered.",
    explanation: [
      "A foreign-owned factory’s production is in Australia’s GDP, but some profits may accrue to foreign residents. An Australian resident’s foreign investment income is relevant to GNI rather than Australian domestic production.",
      "The two can differ in an open economy, so do not silently replace one with the other.",
    ],
    whyItMatters:
      "It is a direct test of the location-versus-residency distinction in national accounting.",
    prerequisites: ["gross-domestic-product", "income", "exports"],
    relatedConcepts: ["current-account", "primary-income", "gdp-welfare"],
    sourceRefs: [
      L("lecture-w1-l1", 53, "GDP income approach and domestic production."),
      T(18, "GDP definition by place of production."),
    ],
    contrasts: [
      {
        conceptId: "gross-domestic-product",
        title: "GDP versus GNI",
        difference: "GDP is location-based production; GNI is resident-based income.",
      },
    ],
  }),
  c({
    id: "gdp-welfare",
    name: "GDP and economic welfare",
    aliases: ["GDP and wellbeing", "GDP welfare"],
    searchTerms: ["is GDP a good measure of living standards", "limitations of GDP"],
    chapters: [1],
    tags: ["chapter-1", "welfare"],
    summary:
      "GDP measures market-valued current production, so it is useful for activity but incomplete as a measure of wellbeing.",
    intuition:
      "GDP records what passes through the production accounts; it does not automatically record leisure, distribution, household work, environmental costs, or happiness.",
    explanation: [
      "Real GDP per capita can correlate with material resources, but averages hide inequality and non-market outcomes. Some public services are imputed at cost, and some digital or household activity is difficult to measure.",
      "The correct conclusion is not that GDP is useless; it is that GDP answers a narrower question than overall welfare.",
    ],
    whyItMatters:
      "It prevents normative conclusions from being smuggled into a production statistic.",
    prerequisites: ["gross-domestic-product", "real-gdp", "gdp-per-capita"],
    relatedConcepts: ["business-cycle", "economic-growth", "gdp-vs-gni"],
    sourceRefs: [
      L("lecture-w1-l1", 81, "Lecture omissions from GDP relevant to welfare."),
      T(32, "GDP per capita and welfare limitations."),
    ],
  }),
  c({
    id: "population",
    name: "Population",
    aliases: ["total population"],
    searchTerms: ["number of people", "residents"],
    chapters: [1, 2, 10],
    tags: ["foundation", "chapter-2", "growth"],
    summary:
      "Population is the number of people in the relevant geographic or statistical group.",
    intuition:
      "It is the broad pool from which labour-market categories and per-person output measures are constructed.",
    explanation: [
      "Not everyone in the population is in the working-age population or labour force. Definitions are statistical rules, not moral judgments about who is contributing.",
      "Population growth affects real GDP per capita and can affect labour supply and potential output.",
    ],
    whyItMatters:
      "It is the denominator or starting group for GDP per capita, labour-force classifications, and participation.",
    prerequisites: ["stock"],
    relatedConcepts: [
      "working-age-population",
      "labour-force",
      "gdp-per-capita",
      "participation-rate",
    ],
    sourceRefs: [
      L("lecture-w1-l1", 78, "Population in the real GDP per-capita measure."),
      L(
        "lecture-w1-l2",
        22,
        "Labour-market classification begins with the population.",
      ),
      T(56, "Labour-market definitions."),
    ],
  }),
  c({
    id: "working-age-population",
    name: "Working-age population",
    aliases: ["working age", "working-age people"],
    searchTerms: ["people eligible for labour statistics", "adult population base"],
    chapters: [2],
    tags: ["chapter-2", "labour"],
    summary:
      "The working-age population is the population group used as the potential base for labour-force statistics.",
    intuition:
      "It is a statistical container: people inside it can be employed, unemployed, or not in the labour force.",
    explanation: [
      "The course uses the working-age population rather than total population for participation and employment-to-population calculations. Exact age boundaries are set by the statistical definition.",
      "Being of working age does not mean a person is in the labour force; active job search and availability matter for unemployment classification.",
    ],
    whyItMatters:
      "It keeps the labour-force denominator separate from the unemployment-rate denominator.",
    prerequisites: ["population", "stock"],
    relatedConcepts: [
      "labour-force",
      "not-in-labour-force",
      "participation-rate",
      "employment-population-ratio",
    ],
    sourceRefs: [
      L("lecture-w1-l2", 22, "Labour-market classification diagram."),
      T(56, "Labour Market Definitions table."),
    ],
  }),
  c({
    id: "employment",
    name: "Employment",
    aliases: ["employed", "employed people", "jobs"],
    searchTerms: ["working for pay", "people with work"],
    chapters: [2],
    tags: ["chapter-2", "labour"],
    summary:
      "Employment means doing paid work or meeting the course’s statistical criteria for having a job.",
    intuition:
      "The classification asks what a person actually did during the reference period, not whether they feel economically useful.",
    explanation: [
      "A person can be employed while working part-time or temporarily absent from a job under the survey rules. Employment is a headcount or flow measure depending on how it is used.",
      "The employment-to-population ratio uses working-age population as its denominator; the unemployment rate does not.",
    ],
    whyItMatters:
      "Employment is one of the mutually exclusive labour-market categories used to construct the labour force and rates.",
    prerequisites: ["working-age-population", "flow"],
    relatedConcepts: [
      "unemployed",
      "labour-force",
      "employment-population-ratio",
      "labour-market-flows",
    ],
    sourceRefs: [
      L("lecture-w1-l2", 23, "ABS Labour Force Survey definitions."),
      T(56, "Labour-market definitions."),
    ],
  }),
  c({
    id: "unemployed",
    name: "Unemployed",
    aliases: ["unemployment", "unemployed person", "jobless"],
    searchTerms: ["jobless and actively looking", "without work seeking work"],
    chapters: [2],
    tags: ["chapter-2", "labour", "high-yield"],
    summary:
      "An unemployed person has no job, is available for work, and is actively seeking work under the statistical definition.",
    intuition:
      "Not having a job is necessary but not sufficient: someone who is not looking or not available is classified outside the labour force.",
    explanation: [
      "The unemployment rate divides unemployed people by the labour force, not by the whole working-age population. This makes the denominator a key part of the definition.",
      "Unemployment can be frictional, structural, or cyclical, depending on why the job search or joblessness occurs.",
    ],
    whyItMatters:
      "It is the numerator of the unemployment rate and a central outcome of the business cycle and labour-market model.",
    prerequisites: ["working-age-population", "employment"],
    relatedConcepts: [
      "employment",
      "not-in-labour-force",
      "unemployment-rate",
      "cyclical-unemployment",
    ],
    sourceRefs: [
      L("lecture-w1-l2", 25, "Labour-force and unemployment definitions."),
      T(56, "Labour Market Definitions table."),
    ],
    misconceptions: [
      "A discouraged worker may be jobless but outside the measured labour force if they stop actively searching.",
    ],
  }),
  c({
    id: "not-in-labour-force",
    name: "Not in the labour force",
    aliases: ["NLF", "outside the labour force", "not in labour force"],
    searchTerms: [
      "neither employed nor actively seeking work",
      "outside labour statistics",
    ],
    chapters: [2],
    tags: ["chapter-2", "labour", "high-yield"],
    summary:
      "A person not in the labour force is neither employed nor counted as unemployed.",
    intuition:
      "The category includes people who are not working and not actively seeking or available for work under the survey definition; it is not a synonym for lazy or retired.",
    explanation: [
      "Students, carers, retirees, and discouraged workers can be in this category, depending on their actual search and availability behaviour.",
      "When an unemployed person stops searching, unemployment may fall while the labour force also shrinks. That is why the unemployment rate must be interpreted with participation.",
    ],
    whyItMatters:
      "It is the most common source of confusion between unemployment and non-participation.",
    prerequisites: ["working-age-population", "employment", "unemployed"],
    relatedConcepts: [
      "labour-force",
      "participation-rate",
      "discouraged-workers",
      "unemployment-rate",
    ],
    sourceRefs: [
      L("lecture-w1-l2", 26, "Not-in-labour-force category."),
      T(56, "Labour Market Definitions."),
    ],
    contrasts: [
      {
        conceptId: "unemployed",
        title: "Unemployed versus outside the labour force",
        difference:
          "Unemployed people are actively seeking and available for work; people outside the labour force are not counted as either employed or unemployed.",
      },
    ],
  }),
  c({
    id: "labour-force",
    name: "Labour force",
    aliases: ["LF", "labour-force population", "workforce"],
    searchTerms: ["employed plus unemployed", "people participating in work market"],
    chapters: [2],
    tags: ["chapter-2", "labour", "high-yield"],
    summary:
      "The labour force is employed people plus unemployed people who are actively seeking and available for work.",
    intuition:
      "It is the active pool in the labour market, not everyone of working age and not everyone who would like a job in some abstract sense.",
    explanation: [
      "People outside the labour force are excluded from both the numerator and denominator of the unemployment rate. Participation measures how much of the working-age population is in the labour force.",
      "Labour-force flows, such as entering, leaving, becoming employed, and becoming unemployed, help explain the natural and cyclical unemployment rates.",
    ],
    whyItMatters:
      "It is the denominator for unemployment and the numerator for participation, so classification errors propagate into both rates.",
    prerequisites: ["employment", "unemployed", "working-age-population"],
    relatedConcepts: [
      "unemployment-rate",
      "participation-rate",
      "labour-market-flows",
      "not-in-labour-force",
    ],
    sourceRefs: [
      L("lecture-w1-l2", 25, "Labour-force definition."),
      T(56, "Labour Market Definitions."),
    ],
    equations: [
      {
        label: "Labour force",
        expression: "LF = E + U",
        variables: [
          { symbol: "LF", meaning: "labour force" },
          { symbol: "E", meaning: "employed people" },
          { symbol: "U", meaning: "unemployed people" },
        ],
        interpretation:
          "The identity is a classification rule; it does not say every working-age person is in LF.",
      },
    ],
  }),
  c({
    id: "unemployment-rate",
    name: "Unemployment rate",
    aliases: ["unemployment rate", "u"],
    searchTerms: ["jobless rate", "share of labour force without work"],
    chapters: [2],
    tags: ["chapter-2", "labour", "calculation", "high-yield"],
    summary:
      "The unemployment rate is unemployed people as a percentage of the labour force.",
    intuition:
      "It asks: among people participating in the labour market, what share is currently without a job but searching and available?",
    explanation: [
      "The denominator is LF = employed + unemployed, not the working-age population. A falling unemployment rate can reflect more jobs, fewer job seekers, or both.",
      "Participation and the employment-to-population ratio provide complementary information about people outside the labour force.",
    ],
    whyItMatters:
      "It is a high-frequency labour-market indicator and enters the course’s natural-rate and Okun-law relationships.",
    prerequisites: ["unemployed", "labour-force", "percentage"],
    relatedConcepts: [
      "participation-rate",
      "employment-population-ratio",
      "natural-rate-unemployment",
      "okun-law",
    ],
    sourceRefs: [
      L("lecture-w1-l2", 29, "Unemployment-rate formula."),
      T(58, "Labour-force data and unemployment rate."),
    ],
    equations: [
      {
        label: "Unemployment rate",
        expression: "u = U / LF × 100",
        variables: [
          { symbol: "U", meaning: "unemployed people" },
          { symbol: "LF", meaning: "labour force" },
        ],
        interpretation:
          "Use the labour force as the denominator; changing the denominator changes the statistic.",
      },
    ],
  }),
  c({
    id: "participation-rate",
    name: "Participation rate",
    aliases: ["labour-force participation rate", "participation"],
    searchTerms: [
      "share of working-age population in labour force",
      "workforce participation",
    ],
    chapters: [2],
    tags: ["chapter-2", "labour", "calculation"],
    summary:
      "The participation rate is the labour force as a percentage of the working-age population.",
    intuition:
      "It tells you how large the active labour-market pool is relative to the people who could potentially be in it.",
    explanation: [
      "A person can move from unemployed to outside the labour force without getting a job. Participation reveals that movement even if the unemployment rate falls.",
      "The participation rate is different from the employment-to-population ratio because the labour force includes unemployed job seekers.",
    ],
    whyItMatters:
      "It prevents the unemployment rate from being read as a complete measure of labour-market health.",
    prerequisites: ["labour-force", "working-age-population", "percentage"],
    relatedConcepts: [
      "unemployment-rate",
      "employment-population-ratio",
      "not-in-labour-force",
    ],
    sourceRefs: [
      L("lecture-w1-l2", 29, "Participation and employment-population ratios."),
      T(61, "Participation-rate figure."),
    ],
    equations: [
      {
        label: "Participation rate",
        expression: "LF / working-age population × 100",
        variables: [
          { symbol: "LF", meaning: "labour force" },
          {
            symbol: "working-age population",
            meaning: "statistical working-age group",
          },
        ],
        interpretation:
          "The statistic rises when more working-age people enter the active labour market, even before they find jobs.",
      },
    ],
  }),
  c({
    id: "employment-population-ratio",
    name: "Employment-to-population ratio",
    aliases: ["employment-population ratio", "employment rate"],
    searchTerms: ["share of working-age people with jobs", "employment share"],
    chapters: [2],
    tags: ["chapter-2", "labour", "calculation"],
    summary:
      "The employment-to-population ratio is employed people as a percentage of the working-age population.",
    intuition:
      "Unlike the unemployment rate, it asks about jobs among the whole working-age group, including people outside the labour force.",
    explanation: [
      "It can fall because employment falls or because the working-age population grows faster. It is often useful beside participation and unemployment.",
      "A high participation rate with a high unemployment rate and a low employment-to-population ratio describes a different situation from low participation with low unemployment.",
    ],
    whyItMatters:
      "It helps diagnose whether a change in unemployment reflects jobs, job search, or labour-force exit.",
    prerequisites: ["employment", "working-age-population", "percentage"],
    relatedConcepts: ["participation-rate", "unemployment-rate", "labour-force"],
    sourceRefs: [
      L("lecture-w1-l2", 29, "Important labour-market ratios."),
      T(61, "Participation and employment-to-population figure."),
    ],
    equations: [
      {
        label: "Employment-to-population ratio",
        expression: "E / working-age population × 100",
        variables: [
          { symbol: "E", meaning: "employed people" },
          {
            symbol: "working-age population",
            meaning: "statistical working-age group",
          },
        ],
        interpretation:
          "The denominator includes people who are not participating in the labour force.",
      },
    ],
  }),
  c({
    id: "labour-market-flows",
    name: "Labour-market flows",
    aliases: ["labour flows", "flows into unemployment", "employment flows"],
    searchTerms: [
      "people moving between labour categories",
      "job finding and separation",
    ],
    chapters: [2],
    tags: ["chapter-2", "labour", "dynamics"],
    summary:
      "Labour-market flows are movements between employment, unemployment, and non-participation over time.",
    intuition:
      "The unemployment rate is a snapshot; flows explain how people enter and leave that snapshot.",
    explanation: [
      "Separations can move employed people into unemployment, job finding can move unemployed people into employment, and discouraged search can move people out of the measured labour force.",
      "The natural unemployment rate reflects steady flows between jobs and unemployment even when cyclical demand is not weak.",
    ],
    whyItMatters:
      "The course uses flows to explain frictional unemployment, natural unemployment, and why a rate can change without a matching change in employment.",
    prerequisites: ["employment", "unemployed", "not-in-labour-force", "flow"],
    relatedConcepts: [
      "frictional-unemployment",
      "natural-rate-unemployment",
      "discouraged-workers",
    ],
    sourceRefs: [
      L("lecture-w1-l2", 40, "Types of unemployment and labour-market movements."),
      T(64, "Unemployment and labour-market dynamics."),
    ],
  }),
  c({
    id: "frictional-unemployment",
    name: "Frictional unemployment",
    aliases: ["search unemployment", "frictional unemployment"],
    searchTerms: ["between jobs", "short-term job search"],
    chapters: [2],
    tags: ["chapter-2", "labour"],
    summary:
      "Frictional unemployment is short-term unemployment while workers and suitable jobs are being matched.",
    intuition:
      "Even a healthy labour market takes time to search, interview, move, and learn whether a job is a good fit.",
    explanation: [
      "It can be beneficial because matching takes time and can improve productivity. Better information and lower search costs can reduce its duration.",
      "It is part of the natural rate because some search continues when cyclical demand is normal.",
    ],
    whyItMatters:
      "It distinguishes normal job search from unemployment caused by a recession or a structural mismatch.",
    prerequisites: ["unemployed", "labour-market-flows"],
    relatedConcepts: [
      "structural-unemployment",
      "cyclical-unemployment",
      "natural-rate-unemployment",
    ],
    sourceRefs: [
      L("lecture-w1-l2", 41, "Frictional or search unemployment."),
      T(62, "Types of unemployment."),
    ],
  }),
  c({
    id: "structural-unemployment",
    name: "Structural unemployment",
    aliases: ["structural unemployment", "skills mismatch"],
    searchTerms: ["jobs and workers do not match", "industry change unemployment"],
    chapters: [2],
    tags: ["chapter-2", "labour"],
    summary:
      "Structural unemployment arises when workers’ skills, locations, or institutions do not match available jobs.",
    intuition:
      "Vacancies can exist at the same time as unemployment because the people looking and the jobs available are not interchangeable immediately.",
    explanation: [
      "Technological change, trade, changing demand, or institutional features can create structural mismatch. Training, mobility, and improved matching may reduce it.",
      "Like frictional unemployment, it is usually included in the natural rate rather than the cyclical component.",
    ],
    whyItMatters:
      "It keeps a high unemployment rate from being interpreted as entirely removable by demand stimulus.",
    prerequisites: ["unemployed", "labour-market-flows"],
    relatedConcepts: [
      "frictional-unemployment",
      "cyclical-unemployment",
      "natural-rate-unemployment",
      "productivity",
    ],
    sourceRefs: [
      L("lecture-w1-l2", 43, "Structural unemployment definition."),
      T(63, "Structural change and unemployment."),
    ],
  }),
  c({
    id: "cyclical-unemployment",
    name: "Cyclical unemployment",
    aliases: ["cyclical unemployment", "demand-deficient unemployment"],
    searchTerms: ["recession unemployment", "unemployment from weak demand"],
    chapters: [2],
    tags: ["chapter-2", "labour", "business-cycle"],
    summary:
      "Cyclical unemployment is unemployment associated with fluctuations in aggregate economic activity.",
    intuition:
      "When demand for output is weak, firms need fewer workers, so job losses and weak hiring raise unemployment above its normal level.",
    explanation: [
      "Cyclical unemployment is linked to the output gap and can be positive in a contractionary gap. It is distinct from search and skills mismatch.",
      "When output returns toward potential, cyclical unemployment can fall without every worker changing skills or search behaviour.",
    ],
    whyItMatters:
      "It connects labour statistics to GDP, the business cycle, Okun’s law, and stabilisation policy.",
    prerequisites: ["unemployed", "business-cycle", "output-gap"],
    relatedConcepts: [
      "natural-rate-unemployment",
      "okun-law",
      "potential-output",
      "aggregate-demand",
    ],
    sourceRefs: [
      L("lecture-w1-l2", 44, "Cyclical unemployment and economic activity."),
      T(64, "Recessions and unemployment."),
    ],
  }),
  c({
    id: "natural-rate-unemployment",
    name: "Natural rate of unemployment",
    aliases: ["natural unemployment", "u*", "natural rate"],
    searchTerms: ["normal unemployment", "frictional plus structural unemployment"],
    chapters: [2],
    tags: ["chapter-2", "labour", "high-yield"],
    summary:
      "The natural rate is the unemployment rate that remains when cyclical unemployment is zero.",
    intuition:
      "A fully employed economy can still have people changing jobs or finding that their skills do not fit available vacancies.",
    explanation: [
      "In the course, the natural rate is associated with frictional and structural unemployment. Actual unemployment can be above or below it when the output gap is not zero.",
      "It is not a claim that unemployment is natural, desirable, or fixed forever; institutions and matching conditions can change it.",
    ],
    whyItMatters:
      "It is the benchmark used to separate cyclical unemployment and interpret Okun’s law.",
    prerequisites: [
      "frictional-unemployment",
      "structural-unemployment",
      "cyclical-unemployment",
    ],
    relatedConcepts: [
      "unemployment-rate",
      "okun-law",
      "potential-output",
      "labour-market-flows",
    ],
    sourceRefs: [
      L("lecture-w1-l2", 47, "Natural rate of unemployment."),
      T(66, "Natural unemployment and potential output."),
    ],
    equations: [
      {
        label: "Unemployment decomposition",
        expression: "cyclical unemployment = u − u*",
        variables: [
          { symbol: "u", meaning: "actual unemployment rate" },
          { symbol: "u*", meaning: "natural unemployment rate" },
        ],
        interpretation:
          "The sign indicates whether unemployment is above or below its natural benchmark.",
      },
    ],
  }),
  c({
    id: "potential-output",
    name: "Potential output",
    aliases: ["potential GDP", "Y*", "full-employment output"],
    searchTerms: ["sustainable output", "output at normal labour utilisation"],
    chapters: [2, 8],
    tags: ["chapter-2", "chapter-8", "output", "high-yield"],
    summary:
      "Potential output is the level of output the economy can produce sustainably with normal utilisation of resources.",
    intuition:
      "It is a benchmark for capacity, not the maximum imaginable output and not necessarily the output currently produced.",
    explanation: [
      "Actual real GDP can be below potential in a contractionary output gap or above it in an expansionary gap. Potential changes when productive capacity, labour supply, capital, or productivity changes.",
      "The AD-AS model uses potential output to describe long-run equilibrium and the inflation pressure associated with output gaps.",
    ],
    whyItMatters:
      "Potential output links GDP measurement to unemployment, Okun’s law, AD-AS adjustment, and policy stabilisation.",
    prerequisites: ["real-gdp", "labour-force", "capital"],
    relatedConcepts: [
      "output-gap",
      "cyclical-unemployment",
      "aggregate-supply",
      "economic-growth",
    ],
    sourceRefs: [
      L("lecture-w1-l2", 51, "Potential output definition."),
      T(66, "Potential GDP and output gap figures."),
    ],
  }),
  c({
    id: "output-gap",
    name: "Output gap",
    aliases: ["output gap", "Y minus Y*", "contractionary gap"],
    searchTerms: [
      "actual output relative to potential",
      "below or above potential GDP",
    ],
    chapters: [2, 8],
    tags: ["chapter-2", "chapter-8", "output", "high-yield"],
    summary: "The output gap compares actual real GDP with potential output.",
    intuition:
      "It tells you whether the economy is producing less or more than its sustainable benchmark, not merely whether output is rising or falling.",
    explanation: [
      "A contractionary gap means actual output is below potential; an expansionary gap means it is above potential. The level of output can rise while the gap remains negative if potential rises faster.",
      "Output gaps are connected to cyclical unemployment and inflation pressure, but the exact relationship is model-dependent.",
    ],
    whyItMatters:
      "It is the bridge between the labour-market cycle, AD-AS, and monetary/fiscal policy objectives.",
    prerequisites: ["real-gdp", "potential-output", "percentage-change"],
    relatedConcepts: [
      "cyclical-unemployment",
      "okun-law",
      "aggregate-demand",
      "inflation-dynamics",
    ],
    sourceRefs: [
      L("lecture-w1-l2", 55, "Output-gap definition and policy interpretation."),
      T(66, "Output-gap figure."),
    ],
    equations: [
      {
        label: "Simple output gap",
        expression: "Y − Y*",
        variables: [
          { symbol: "Y", meaning: "actual real GDP" },
          { symbol: "Y*", meaning: "potential output" },
        ],
        interpretation:
          "A percentage version divides the gap by potential output; the sign tells you whether output is below or above potential.",
      },
    ],
  }),
  c({
    id: "okun-law",
    name: "Okun’s law",
    aliases: ["Okun law", "Okun's law"],
    searchTerms: ["output gap and unemployment relationship", "GDP unemployment rule"],
    chapters: [2],
    tags: ["chapter-2", "labour", "calculation"],
    summary:
      "Okun’s law is the course’s empirical relationship linking an output gap with cyclical unemployment.",
    intuition:
      "When output is weak relative to potential, firms generally need fewer workers, so cyclical unemployment tends to be higher.",
    explanation: [
      "It is an approximate quantitative relationship, not an accounting identity. The coefficient is estimated and can differ across economies and periods.",
      "Use the course’s sign convention carefully: a contractionary output gap is associated with positive cyclical unemployment, while an expansionary gap is associated with unemployment below the natural rate.",
    ],
    whyItMatters:
      "It turns the output gap into a labour-market prediction and is a common short calculation.",
    prerequisites: ["output-gap", "cyclical-unemployment", "rate"],
    relatedConcepts: [
      "natural-rate-unemployment",
      "unemployment-rate",
      "potential-output",
    ],
    sourceRefs: [
      L("lecture-w1-l2", 58, "Okun’s law and quantitative relationship."),
      T(68, "Estimate of Okun’s law."),
    ],
    equations: [
      {
        label: "Course-style relationship",
        expression: "cyclical unemployment ≈ −β × output gap",
        variables: [
          { symbol: "β", meaning: "positive estimated Okun coefficient" },
          { symbol: "output gap", meaning: "actual output relative to potential" },
        ],
        interpretation:
          "The negative sign captures the inverse relationship; use the exact equation and units provided in the question.",
      },
    ],
  }),
  c({
    id: "nominal-interest-rate",
    name: "Nominal interest rate",
    aliases: ["nominal interest", "nominal rate", "i"],
    searchTerms: ["money return", "interest rate before inflation adjustment"],
    chapters: [3, 7],
    tags: ["chapter-3", "chapter-7", "finance", "high-yield"],
    summary:
      "A nominal interest rate is the money return on lending before adjusting for inflation.",
    intuition:
      "It tells you how many extra dollars are promised, not how many extra goods those dollars can buy.",
    explanation: [
      "A lender who receives a 5% nominal return has more dollars, but if prices rose by 4%, the purchasing-power gain is much smaller.",
      "The RBA directly targets a nominal short-term cash rate, while saving and investment decisions are more closely related to the real rate.",
    ],
    whyItMatters:
      "It is one side of the Fisher relationship and the distinction between the RBA’s instrument and real economic incentives.",
    prerequisites: ["interest-rate", "nominal", "inflation"],
    relatedConcepts: [
      "real-interest-rate",
      "fisher-relationship",
      "cash-rate",
      "bond-yield",
    ],
    sourceRefs: [
      L("lecture-w2-l1", 54, "Nominal interest rate definition."),
      T(84, "Nominal and real interest rates."),
    ],
  }),
  c({
    id: "real-interest-rate",
    name: "Real interest rate",
    aliases: ["real interest", "real rate", "r"],
    searchTerms: ["inflation-adjusted borrowing cost", "purchasing-power return"],
    chapters: [3, 7, 8],
    tags: ["chapter-3", "chapter-7", "finance", "high-yield"],
    summary:
      "A real interest rate measures the return or cost of lending and borrowing in purchasing-power terms.",
    intuition:
      "It asks how many additional goods or services the repayment can buy after the price level has changed.",
    explanation: [
      "The ex-post real rate uses realised inflation; the expected real rate uses inflation people expected when the contract was made. The latter is important for decisions made before the outcome is known.",
      "For small rates, the course uses real rate ≈ nominal rate − inflation. The exact Fisher relationship compounds the terms.",
      "A higher real rate usually makes interest-sensitive borrowing and investment less attractive, conditional on the model’s other variables.",
    ],
    whyItMatters:
      "The real rate is the key channel from monetary policy to saving, investment, PAE, AD, and exchange rates.",
    prerequisites: ["nominal-interest-rate", "inflation", "real"],
    relatedConcepts: [
      "fisher-relationship",
      "ex-post-real-rate",
      "expected-real-rate",
      "user-cost-capital",
      "monetary-transmission",
    ],
    mechanism: [
      "nominal return is stated in dollars",
      "prices change during the period",
      "the purchasing-power return differs from the money return",
      "planned saving or investment responds to the real, not merely nominal, incentive",
    ],
    equations: [
      {
        label: "Approximate real rate",
        expression: "r ≈ i − πᵉ",
        variables: [
          { symbol: "r", meaning: "expected real interest rate, percent per period" },
          { symbol: "i", meaning: "nominal interest rate, percent per period" },
          { symbol: "πᵉ", meaning: "expected inflation rate, percent per period" },
        ],
        interpretation:
          "The approximation is useful for small rates; it subtracts the expected loss of purchasing power from the nominal return.",
      },
    ],
    misconceptions: [
      "A higher nominal rate need not mean a higher real rate if expected inflation rises at the same time.",
      "The cash rate is a particular nominal policy instrument; it is not identical to every real interest rate in the economy.",
    ],
    sourceRefs: [
      L("lecture-w2-l1", 56, "Real interest rate in purchasing-power terms."),
      L("lecture-w7-l1", 11, "Nominal and real rates in the RBA transmission model."),
      T(86, "Ex-post and expected real rates."),
    ],
  }),
  c({
    id: "ex-post-real-rate",
    name: "Ex-post real interest rate",
    aliases: ["ex post real rate", "realised real interest rate"],
    searchTerms: ["real rate using actual inflation", "after-the-fact real return"],
    chapters: [3],
    tags: ["chapter-3", "finance"],
    summary:
      "The ex-post real rate uses inflation that actually occurred during the contract period.",
    intuition:
      "It is the purchasing-power result you can calculate after observing what happened.",
    explanation: [
      "A contract is usually made using an expected real rate, but the realised return can differ when actual inflation surprises borrowers and lenders.",
      "The course’s approximate expression subtracts actual inflation from the nominal rate for the ex-post calculation.",
    ],
    whyItMatters:
      "It separates a realised measurement from the expected incentive that influenced the original decision.",
    prerequisites: ["real-interest-rate", "inflation"],
    relatedConcepts: ["expected-real-rate", "inflation", "fisher-relationship"],
    sourceRefs: [
      L("lecture-w2-l1", 61, "Ex-post real-rate calculation."),
      T(86, "Ex-post and expected real rate section."),
    ],
    contrasts: [
      {
        conceptId: "expected-real-rate",
        title: "Ex-post versus expected real rate",
        difference:
          "Ex-post uses realised inflation; expected real rate uses inflation anticipated when the loan or asset was priced.",
      },
    ],
  }),
  c({
    id: "expected-real-rate",
    name: "Expected real interest rate",
    aliases: ["expected real rate", "ex ante real rate", "rᵉ"],
    searchTerms: [
      "real rate before inflation is known",
      "decision-relevant real borrowing cost",
    ],
    chapters: [3, 7],
    tags: ["chapter-3", "chapter-7", "finance"],
    summary:
      "The expected real rate is the nominal rate minus expected inflation, approximately for small rates.",
    intuition:
      "It is the real price people expect when they choose whether to borrow, lend, save, or invest today.",
    explanation: [
      "The expected rate can differ from the ex-post rate because actual inflation can surprise people. Expected inflation is therefore part of the monetary-policy transmission story.",
      "If nominal rates are unchanged and expected inflation rises, the expected real rate falls, all else equal.",
    ],
    whyItMatters:
      "It explains why nominal policy rates do not mechanically determine real spending without expectations.",
    prerequisites: ["nominal-interest-rate", "inflation", "expectations"],
    relatedConcepts: [
      "ex-post-real-rate",
      "fisher-relationship",
      "inflation-expectations",
      "real-rate-channel",
    ],
    sourceRefs: [
      L("lecture-w2-l1", 65, "Fisher effect and expected inflation."),
      L("lecture-w7-l1", 23, "Cash rate, expected inflation, and real rate."),
      T(86, "Expected real rate."),
    ],
  }),
  c({
    id: "inflation-expectations",
    name: "Inflation expectations",
    aliases: ["expected inflation", "πᵉ", "inflation expectation"],
    searchTerms: ["what people think inflation will be", "anticipated inflation"],
    chapters: [1, 3, 7, 8],
    tags: ["chapter-1", "chapter-7", "expectations"],
    summary:
      "Inflation expectations are beliefs about future changes in the general price level.",
    intuition:
      "A worker, lender, or firm chooses a contract today while future prices are still unknown, so the anticipated price change affects today’s decisions.",
    explanation: [
      "Expected inflation is not the same as actual inflation. It enters the expected real rate and can influence wage setting, bond yields, and the position of short-run aggregate supply.",
      "The course uses expectations in the Fisher relationship and in inflation dynamics; the exact forecasting rule depends on the model.",
    ],
    whyItMatters:
      "Expectations explain why policy credibility and future prices matter for current nominal rates and inflation.",
    prerequisites: ["inflation", "expectations"],
    relatedConcepts: [
      "expected-real-rate",
      "fisher-relationship",
      "adaptive-expectations",
      "yield-curve",
    ],
    sourceRefs: [
      L("lecture-w2-l1", 66, "Fisher effect with expected inflation."),
      L("lecture-w7-l2", 15, "Expected inflation in aggregate supply."),
      T(221, "Expected inflation and AS."),
    ],
  }),
  c({
    id: "expectations",
    name: "Expectations",
    aliases: ["economic expectations", "beliefs about the future"],
    searchTerms: ["plans based on future beliefs", "anticipated outcomes"],
    chapters: [0],
    tags: ["foundation", "expectations"],
    summary:
      "Expectations are beliefs about future economic variables used when making decisions today.",
    intuition:
      "Borrowers and firms must choose now even though future prices, income, and interest rates have not been observed.",
    explanation: [
      "An expectation is not guaranteed to be correct. The course distinguishes expected and realised inflation and uses explicit expectation rules in some models.",
      "Expectations can affect current prices, investment plans, wage decisions, bond yields, and the response to policy announcements.",
    ],
    whyItMatters:
      "It is a small background node that stops expected inflation and the expectations hypothesis from appearing without explanation.",
    prerequisites: [],
    relatedConcepts: [
      "inflation-expectations",
      "adaptive-expectations",
      "expected-real-rate",
      "yield-curve",
    ],
    sourceRefs: [T(86, "Expected real rates and inflation expectations.")],
  }),
  c({
    id: "fisher-relationship",
    name: "Fisher relationship",
    aliases: ["Fisher effect", "Fisher equation", "Fisher relationship"],
    searchTerms: [
      "nominal rate equals real rate plus expected inflation",
      "i equals r plus pi expected",
    ],
    chapters: [3, 7],
    tags: ["chapter-3", "chapter-7", "finance", "calculation"],
    summary:
      "The Fisher relationship connects a nominal interest rate with a real rate and expected inflation.",
    intuition:
      "A lender wants compensation both for waiting in real terms and for the fact that the dollars repaid may buy less in the future.",
    explanation: [
      "For small rates the course writes i ≈ r + πᵉ, or r ≈ i − πᵉ. The exact relationship is multiplicative: (1+i) = (1+r)(1+πᵉ).",
      "The equation is a relationship among rates, not a claim that the RBA directly controls the real rate one-for-one.",
    ],
    whyItMatters:
      "It is the calculation and intuition behind the nominal/real distinction and the cash-rate transmission mechanism.",
    prerequisites: [
      "nominal-interest-rate",
      "expected-real-rate",
      "inflation-expectations",
      "algebraic-substitution",
    ],
    relatedConcepts: [
      "real-interest-rate",
      "ex-post-real-rate",
      "cash-rate",
      "monetary-transmission",
    ],
    mechanism: [
      "expected inflation reduces the future purchasing power of a fixed nominal repayment",
      "the nominal rate includes compensation for the real return plus expected inflation",
      "holding the nominal rate fixed, higher expected inflation lowers the expected real rate",
    ],
    equations: [
      {
        label: "Approximate Fisher relationship",
        expression: "i ≈ r + πᵉ",
        variables: [
          { symbol: "i", meaning: "nominal interest rate" },
          { symbol: "r", meaning: "expected real interest rate" },
          { symbol: "πᵉ", meaning: "expected inflation" },
        ],
        interpretation:
          "All rates use the same period and units; the approximation is appropriate for small rates.",
      },
    ],
    misconceptions: [
      "Do not subtract realised inflation when the question asks for the expected real rate.",
      "The Fisher relationship does not make nominal and real rates identical.",
    ],
    sourceRefs: [
      L("lecture-w2-l1", 66, "Fisher effect lecture slide."),
      L("lecture-w7-l1", 24, "Fisher effect in the RBA/PAE model."),
      T(88, "Fisher effect figure and equation."),
    ],
  }),
  c({
    id: "capital-stock",
    name: "Capital stock",
    aliases: ["stock of capital", "productive capital stock"],
    searchTerms: ["machines and structures currently available", "K stock"],
    chapters: [3, 10],
    tags: ["chapter-3", "chapter-10", "growth"],
    summary:
      "The capital stock is the amount of productive capital available at a point in time.",
    intuition:
      "It is the economy’s current toolkit. New investment adds tools, while depreciation removes or reduces their productive value.",
    explanation: [
      "Capital stock is a stock variable; investment and depreciation are flows that change it. Gross investment replaces worn capital and expands the stock only after depreciation is considered.",
      "A larger capital stock can raise output, but diminishing marginal product means adding capital alone cannot usually sustain unlimited growth in output per worker.",
    ],
    whyItMatters:
      "It links short-run investment expenditure with long-run capital accumulation and growth.",
    prerequisites: ["capital", "stock", "macro-investment"],
    relatedConcepts: [
      "net-investment",
      "capital-accumulation",
      "diminishing-marginal-product",
      "capital-deepening",
    ],
    sourceRefs: [
      L("lecture-w2-l2", 3, "Investment flow and capital stock distinction."),
      T(84, "Investment and capital stock."),
    ],
  }),
  c({
    id: "depreciation",
    name: "Depreciation",
    aliases: ["capital depreciation", "wear and tear"],
    searchTerms: ["loss of capital value", "capital wearing out"],
    chapters: [3, 10],
    tags: ["chapter-3", "chapter-10", "growth"],
    summary:
      "Depreciation is the loss of productive capital through wear, damage, or obsolescence.",
    intuition:
      "A new machine can be added to the toolkit while an old one becomes less useful; net expansion depends on both flows.",
    explanation: [
      "Gross investment counts new capital purchases. Net investment subtracts depreciation and therefore measures the change in capital stock under the simplified accounting.",
      "Everyday appreciation and depreciation of an asset’s market price are not always the same as physical capital depreciation in the production model.",
    ],
    whyItMatters:
      "It explains gross versus net investment and why capital accumulation can slow even when investment remains positive.",
    prerequisites: ["capital-stock", "flow"],
    relatedConcepts: [
      "net-investment",
      "macro-investment",
      "capital-accumulation-limits",
    ],
    sourceRefs: [
      T(84, "Capital stock and investment concepts."),
      L("lecture-w2-l2", 29, "User-cost formula includes depreciation."),
    ],
  }),
  c({
    id: "net-investment",
    name: "Net investment",
    aliases: ["net capital investment", "net investment"],
    searchTerms: ["gross investment minus depreciation", "change in capital stock"],
    chapters: [3],
    tags: ["chapter-3", "calculation"],
    summary: "Net investment is gross investment minus depreciation.",
    intuition:
      "It measures how much larger the productive toolkit becomes after replacing worn-out capital.",
    explanation: [
      "Positive net investment expands the capital stock; zero net investment maintains it; negative net investment means the stock shrinks.",
      "Net investment is a flow. It is not the same as the capital stock, which is the accumulated balance at a date.",
    ],
    whyItMatters:
      "It is a direct stock-flow calculation and a bridge to capital accumulation.",
    prerequisites: ["macro-investment", "depreciation", "capital-stock"],
    relatedConcepts: ["capital-accumulation", "stock", "flow"],
    sourceRefs: [
      L("lecture-w2-l2", 3, "Investment flow and capital stock."),
      T(84, "Investment and capital stock."),
    ],
    equations: [
      {
        label: "Net investment",
        expression: "net investment = gross investment − depreciation",
        variables: [
          {
            symbol: "gross investment",
            meaning: "new capital purchases during the period",
          },
          { symbol: "depreciation", meaning: "capital lost during the period" },
        ],
        interpretation:
          "This is the flow that changes the capital stock in the simple model.",
      },
    ],
  }),
  c({
    id: "capital-accumulation",
    name: "Capital accumulation",
    aliases: ["capital accumulation", "accumulating capital"],
    searchTerms: ["growth of capital stock", "building productive capacity"],
    chapters: [3, 10],
    tags: ["chapter-3", "chapter-10", "growth"],
    summary:
      "Capital accumulation is the process by which investment adds to the capital stock after depreciation.",
    intuition:
      "A society grows its toolkit when new productive assets are added faster than old productive assets wear out.",
    explanation: [
      "It is a dynamic stock-flow process. The same amount of investment can have different effects if the capital stock is large, depreciation is high, or the technology embodied in new capital differs.",
      "The growth chapter warns that capital accumulation alone faces diminishing returns; productivity and ideas matter for sustained growth.",
    ],
    whyItMatters:
      "It is the link between macroeconomic investment, productivity, and long-run output per worker.",
    prerequisites: ["capital-stock", "net-investment", "flow"],
    relatedConcepts: [
      "capital-deepening",
      "diminishing-marginal-product",
      "productivity",
      "economic-growth",
    ],
    sourceRefs: [
      L(
        "lecture-w2-l2",
        3,
        "Capital stock changes through investment and depreciation.",
      ),
      L("lecture-w9-l1", 47, "Sources of economic growth."),
      T(286, "Capital and diminishing marginal product."),
    ],
  }),
] as const;
